### ISSUE TITLE
Events outside of Germany

### ISSUE THREAD

**Issue by schloram** [jweiland-net/events2#10]
Hi @froemken,
it is not possible to add events in countries other than Germany due to a hard coded string at the end of the `$address` array (/Classes/Hooks/CreateMap.php:125). When I wanna add a location in e.g Austria and use maps2 with the Google Maps GeoCode API I always get an error that the address isn't found because it always adds "Deutschland" to the query.

It should be possible to fill out the country as well as `street`, `zip` etc. If it is then not filled the Google Maps GeoCode API will find the best match.

Thanks!

**Comment by froemken** [comment]
Hi @schloram 

thank you for that hint. Yeah, I have really missed to remove that indiviual custom implementation. It should be fixed with current master.

Stefan

**Comment by schloram** [comment]
Quick as always. Thanks! 
But what do you think of adding a country field to every location record so the editor can enter an explicit individual country for every location?

best,
schloram

**Comment by froemken** [comment]
I hope working with static_info_tables would be OK for you.
