### ISSUE TITLE
New Event Image Text

### ISSUE THREAD

**Issue by renekreupl** [jweiland-net/events2#103]
"Hiermit räume ich der Stadt Pforzheim ein einfaches, unbeschränktes Nutzungsrecht an dem hochgeladenen Werk ein. Mit der Nutzung werden keine Rechte von Dritten verletzt."

Hier sollte das Stadt Pforzheim raus ;)

**Comment by froemken** [comment]
Was schlägst Du vor? Den Namen in der Extension Konfiguration bearbeitbar machen? Dann trage ich dort "Stefan Frömken" ein, womit im Text dann steht "Hiermit räume ich der Stefan Frömken ein...". Hmmm. Geht nicht. Demnach müsste ich den kompletten Text bearbeitbar machen. Wen interessiert dieser Text eigentlich? Eigentlich jeden. Trotzdem überlege ich eine Checkbox einzubauen, um das Feature bei Bedarf abzuschalten.

**Comment by froemken** [comment]
Gelöst mit Version 3.5.0.
Text bitte in Zukunft über TypoScript anpassen.
