### ISSUE TITLE
Create Event for non User

### ISSUE THREAD

**Issue by renekreupl** [jweiland-net/events2#104]
Es sollte die einfache Möglichkeit geben auch ohne Frontend Login neue Events zu erstellen.

**Comment by froemken** [comment]
Guten Morgen @renekreupl 

das habe ich aufgegeben, wenn Du dann auf einmal 120.000 Spam-Einträge in der Datenbank hast, macht das alles keinen Spaß mehr.
Wenn Du es brauchst, dann schmeiß die beiden ViewHelper aus New.html Zeile 6 und 8 raus. Damit der AbstractController nicht versucht auf TSFE zuzugreifen, empfehle ich Dir trotzdem eine Benutzergruppe und Benutzer für Events anzulegen. Die UID des Benutzers fügst Du als f:form.hidden noch dem Template hinzu. Dieser enthält die UID des Dummy FE-Benutzers. Damit solltest Du um diese Abfrage drum rum kommen:
https://github.com/jweiland-net/events2/blob/master/Classes/Controller/AbstractController.php#L457

Lieben Gruß und schönen Start in die Woche

Stefan
