### ISSUE TITLE
Hidden records are not displayed in Frontend Editing

### ISSUE THREAD

**Issue by maikm** [jweiland-net/events2#107]
Although "show hidden records" is enabled in Admin Panel settings hidden events2-records are not displayed while Frontend Editing. Therefore a preview is impossible. 

Preview of hidden records worked in version 3.1.2 as expected, all later versions show the same misbehaviour.

**Comment by froemken** [comment]
Thank you for your report. That's right, if you hide an event record NO day related records will be created. That's why you will not see any hidden records in frontend. I just see that I have a hidden column in day table. Hmm...seems that I need a closer view. I keep you informed.

Stefan

**Comment by froemken** [comment]
Hello @maikm 

wow, that was a heavy ticket. Seems that there are some more problems regarding visibility in core:
https://forge.typo3.org/issues/88348
https://forge.typo3.org/issues/86653

For now I have build my own visibility constraint and just released version 3.5.2.

Nice greetings

Stefan
