### ISSUE TITLE
[Feature Request]: Location link to an internal page

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#108]
Hi,
I use the extension on a website where every location is presented with its own page in detail (images, video, calendar and so on). It would be very nice to have the opportunity to link to these pages. Right now you can only link to the location page generated by events2.

**Comment by froemken** [comment]
Hi @Hobokens 

I have just release version 3.6.0 where you can find your feature.

Have fun

Stefan

**Comment by Hobokens** [comment]
thanks a lot.
