### ISSUE TITLE
Grouping events by day fails due to quoting in TYPO3 8.6

### ISSUE THREAD

**Issue by julianhofmann** [jweiland-net/events2#11]
The grouping set by \JWeiland\Events2\Domain\Repository\DayRepository::addGroupingToQuery() fails with an exception:
> #1472074485: Unknown column 'CASE WHEN tx_events2_domain_model_event.event_type != "duration" THEN day ELSE 0 END' in 'group statement'

Tested with TYPO3 8.6.0. Maybe introduction of doctrine changed something

**Comment by froemken** [comment]
Hello Julian,

I have just pushed a new version to master. I have removed the special grouping because it seems that I don't need that anymore. Further I have removed some old Fluid attributes from Templates.

Would be cool, if you can test the new version, too.

Stefan

**Comment by julianhofmann** [comment]
Hi Stefan.

Some quick testings could be completed successfully. Seems to work so far. Thank you!

Julian
