### ISSUE TITLE
organizer - wrong link (FE) for internal pages

### ISSUE THREAD

**Issue by metiny** [jweiland-net/events2#110]
Hello @froemken, thank you for your great extension! 
i have a issue with events2 v. 3.5.2 and TYPO3 8.7.26

in the be i can use the link-wizard and choose a internal page as link for a organizer.
The problem: link in FE is wrong, because in the template file properties.html we have the VH f:link.external for the organizer-link.

result in FE:
`<a title="Organizer" target="_blank" href="t3://page?uid=181">Organizer</a>`

We have to switch to f:link.typolink instead of f:link.external

The problem/solution for the wrong ticket-link #83 and for the feature request #108 is the same.

Thanks a lot!
Metin

**Comment by froemken** [comment]
Hello @metiny 

I just prepare version 3.5.3 where this problem is solved.
Thank you for your help

Stefan
