### ISSUE TITLE
Language problems

### ISSUE THREAD

**Issue by Schweriner** [jweiland-net/events2#116]
Hello and thanks for this great extensions.
I'm having trouble using the extension on a multi-language site (9 LTS). First of all - it does not matter how I configure the sys_language_mode-/overlay (including strict), the event records of the default language will always be shown in the list view.
Another problem occurs when translating an event: An error is shown: 

> 1: Localization failed; "languageField" and "transOrigPointerField" must be defined for the table tx_events2_domain_model_day

**Comment by froemken** [comment]
Good Morning @Schweriner 

thank you for that issue. I'm using translations very seldom, but I can confirm that issue in TYPO3 9. Wow, that will be hard to solve. I keep you informed.

Stefan

**Comment by froemken** [comment]
Hello @Schweriner 

I have just created a new Branch to repair translations:
https://github.com/jweiland-net/events2/tree/implementMultilingual

--> This is currently a NON working branch. I have to adapt multiple methods of Typo3DbQueryParser into events2. Further I have to adapt the same methods for TYPO3 8, too. It will still need some time. Stay tuned.

Stefan

**Comment by froemken** [comment]
Hello @Schweriner 

I have just released a new Version of events2. Can you please test Version 5.0.0, if this problem is solved now?

Stefan

**Comment by Hobokens** [comment]
As far as I can see the problem is solved. Thanks for this release!
