### ISSUE TITLE
event_begin field default not set correctly

### ISSUE THREAD

**Issue by pkerling** [jweiland-net/events2#119]
Hi,

the `event_begin` field of the event domain model uses a call to mktime to set the default value here:

https://github.com/jweiland-net/events2/blob/f86843be288ddeb2e007b749830fdc5ba84805fe/Configuration/TCA/tx_events2_domain_model_event.php#L226

This does not work since the TCA structure is cached in whole, so once it has been cached the day will always stay the same and not switch to the current date until the cache is cleared.

Alternative could be to set it in a hook like news does it: https://github.com/georgringer/news/blob/b73b1db92fbe45a2c396ca4a86840ee0f2dfb377/Classes/Backend/FormDataProvider/NewsRowInitializeNew.php#L54

**Comment by froemken** [comment]
Good point. Thank you.

**Comment by froemken** [comment]
Hello @pkerling 

today I will release a new events2 version where your issue is fixed.
Thank you for your support.

Stefan

**Comment by pkerling** [comment]
That was fast, thanks!
