### ISSUE TITLE
PHP-Kompatibilität?

### ISSUE THREAD

**Issue by joeschi** [jweiland-net/events2#12]
Hallo,
beim Versuch events2 unter Typo3 6.2.30 zu installieren gibt es eine Fehlermeldung. Die PHP-Version ist 5.4.20
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /typo3conf/ext/events2/ext_localconf.php on line 73

**Comment by froemken** [comment]
Thank you for your report. I have just uploaded an updated version
