### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by rtoenjes** [jweiland-net/events2#120]
What I want is a recurring event every friday and saturday in a range of some weeks.

When I set up a recurring event (range about some weeks) and set „no repeat every x weeks, use setting above“ and set „weekday“ to friday and saturday, no event appears.

My fault or a bug?

**Comment by froemken** [comment]
Hello @rtoenjes 

You also have to check at least one or more Checkboxes of 1st, 2nd, 3rd, 4th, 5th. If this option is not filled, no day record will be created.

Stefan
