### ISSUE TITLE
Event Beginn und Event Ende

### ISSUE THREAD

**Issue by Mikel2411** [jweiland-net/events2#125]
Wenn mit der Suchfunktion zum Beispiel vom 1.7 bis 6.7 gesucht wird, werden alle Events außer der 6.7 ausgegeben. Zweites Problem - Event Beginn 1.7 und Event Ende 1.7, also Beginn und Ende am gleichen Tag, dann wird gar kein Event ausgegeben.

**Comment by froemken** [comment]
Moin @Mikel2411 

Danke für das Issue. Ich hab mal ein paar Änderungen eingebaut. Magst Du mal testen, ob das Problem mit dem aktuellsten master hier behoben ist? Wenn ja, dann release ich mal ne neue Version für's TER.

Stefan

**Comment by Mikel2411** [comment]
Jetzt passt es perfekt, Stefan. Damit ist das Problem behoben. Danke für die Mühe.

Michael

**Comment by froemken** [comment]
Thank you for your help.

I have just uploaded the new release to TER

Stefan
