### ISSUE TITLE
TYPO3 8 compatibility broken

### ISSUE THREAD

**Issue by rasgor** [jweiland-net/events2#128]
Hey,

due to the usage of the class ```TYPO3\CMS\Core\Core\Environment``` in ```Classes/Service/JsonLdService.php``` the EXT isn't compatible with TYPO3 8 anymore.

Best regards

**Comment by joeschi** [comment]
I can confim this. v3.7.2 works in Typo3 8, but v3.8.1 breaks.

**Comment by froemken** [comment]
Hello @rasgor @joeschi 

thank you for reporting this issue. I have just uploaded events2 3.8.2 to TER and Composer. This version should fix this issue.

I have added a version_compare to TYPO3 9.2 where Environment class was implemented.

Stefan

**Comment by rasgor** [comment]
Thanks  alot @froemken.
