### ISSUE TITLE
[Feature Request]: Show range of events, even if they are over

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#132]

**Comment by Hobokens** [comment]
The background: Sometimes I want to display all events within a certain period (for example, the current year) in order to inform about the entire event offering. In this case, the calendar should also display events whose dates lie in the past.

**Comment by froemken** [comment]
@Hobokens 

have you tried setting pastMonth-settings in ExtensionManager from 3 months to 12 months?

Stefan

**Comment by Hobokens** [comment]
Thanks for your quick reply.
I know that I can use the jquery calender to go back to older events. But I want to show all the events in the list view.

**Comment by froemken** [comment]
Please remember, events2 always works in a defined timeframe: -x month until +x month. So of cause with some code changes you will get a list of all events for f.e. 2018. But with each day the timeframe will move a day further. In 5 months the links of your events of January until March or April may not work anymore. You can not build something like an archive with events2.

In future we will implement FullCalendar https://fullcalendar.io/#demos as a new plugin. It should be possible to implement a new FullCalendar plugin to implement a year view then.

**Comment by Hobokens** [comment]
Hi @froemken, thank you very much for the explanations. I am curious what the fullcalendar will bring.

**Comment by twurmehl** [comment]
> Please remember, events2 always works in a defined timeframe: -x month until +x month. So of cause with some code changes you will get a list of all events for f.e. 2018. But with each day the timeframe will move a day further. In 5 months the links of your events of January until March or April may not work anymore. You can not build something like an archive with events2.
> 
> In future we will implement FullCalendar https://fullcalendar.io/#demos as a new plugin. It should be possible to implement a new FullCalendar plugin to implement a year view then.

I'd really like a list view of past events too. Either all past events, or from a scpecific range... I think, it's standard of every modern events calendar. Isn't there any chance at all, this feature could be included in a future build?
