### ISSUE TITLE
PHP-Error - Event without location

### ISSUE THREAD

**Issue by joeschi** [jweiland-net/events2#14]
Hallo,
ein Event ohne Veranstaltungsort verursacht in der Detailansicht einen Fehler:
Fatal error: Call to a member function getLocation() on null in /typo3conf/ext/events2/Classes/ViewHelpers/Widget/Controller/ICalendarController.php on line 183

**Comment by froemken** [comment]
Hallo joeschi,

den Fehler hatte ich letztens auch. Liegt an der Maps2 Extension. Der Klassenname in den Modellen muss inkl. Namespaces angegeben werden. Patch für die maps2 habe ich gerade vor 5 Tagen hochgeleden:

https://github.com/jweiland-net/maps2/commit/8e59fd3ec5a0b35166f8b07195399ed8fbb61609

Stefan
