### ISSUE TITLE
Eine Veranstaltung mit unterschiedlichen Terminen

### ISSUE THREAD

**Issue by thomasvollmann** [jweiland-net/events2#142]
Es gibt Veranstaltungen der selben Art, die aber an unterschiedlichen Terminen statt finden.

Gut wäre, wenn ich für eine Veranstaltung nicht nur unterschiedliche Uhrzeiten, sondern auch unterschiedliche Datum angeben kann.

**Comment by froemken** [comment]
Mach das doch. Erstell eine Veranstaltung mit Wiederholung, lass alle Checkboxen für 1. 2. 3. Und mo di mi leer und definiere die gewünschten Datumswerte alle über die Ausschlüsse.

**Comment by thomasvollmann** [comment]
DANKE!!!!!
