### ISSUE TITLE
Wiederholende Veranstaltungen - Listenansicht teilweise ohne Datum

### ISSUE THREAD

**Issue by thomasvollmann** [jweiland-net/events2#144]
Obwohl Termine (Datum) bei "Ausnahmen" festgelegt sind, werden teilweise bei unterschiedlichen Veranstaltungen der Tag in der Listenansicht nicht angezeigt:
![image](https://user-images.githubusercontent.com/55806469/67517417-d9c1c380-f6a2-11e9-9bf7-fbfffd48818c.png)

Ich konnte keine "logik" erkennen, wenn dieses oder jenes eingestellt wird, geht es nicht.

**Comment by froemken** [comment]
Hallo @thomasvollmann 

hast Du die Templates von der events2 überschrieben? Da sind in den letzten Versionen einige Änderungen hinzugekommen. Evtl. nochmal abgleichen, ob die Struktur noch passt. Bitte auch die Upgrade-Section in der Dokumentation mal checken. Da steht drin, welche Änderungen an den Templates nach nem Upgrade durchzuführen sind.

Kontaktiere mich mal auf Slack. Evtl. kannst Du mir auch nen BE-Zugang bauen, damit ich mir das mal anschauen kann.

Da ich keinen Bindestrich sehe, handelt es sich bei Dir nicht um eine Duration und auch keinen wiederkehrenden gemergten Termin. Somit bleibt nur noch das Datum aus {day.day} übrig. Geh mal bitte in die Tabelle tx_events2_domain_model_day. Sortiere mal nach der Spalte `day`, hier müssen alle Felder gefüllt sein. Passt das? Wenn ja, dann mach mal ein <f:debug> auf {day}. Ist day dort gefüllt?

Stefan

**Comment by thomasvollmann** [comment]
Servus!

DANKE für deinen Support!

In der DB Table sind alle Felder bei day ausgefüllt

[cid:image004.png@01D5A91B.72EC2F30]

https://www.mra.at/typo3/
User:     stefan
PW:       only4support!

Es ist ein ganz neues TYPO3 9 und ich habe die letzte events2 Version installiert. Gerade vorhin noch mal direkt das zip File runtergeladen und drücberinstalliert (mit der Folge, dass jetzt alles auf Englisch ist ;/ )

Kurz zur Seite:
Wir sinder Magische Ring Austria (MRA) und somit der österr. Dachverband aller österr. Zauberklubs. Die Ext möchte ich verwenden umm (möglichst) alle österr. Zaubertermine auf einem Blick zu haben.
https://www.mra.at/termine

Ich bin für JEDE Hilfe mehr als dankbar. Anfallende Kosten bitte davor kurz mitteilen, dass muss ich natürlich davor abklären lassen.
Gerne aber namentliche Erwähnung auf der Seite!

Bzgl der Zugangsdaten gehe ich davon aus, dass ich mich verlassen kann ,)

DANKE!

Liebe Grüße aus Österreich
Thomas Vollmann





[Logo 132x132]
Thomas Vollmann
Generalsekretär | Magischer Ring Austria
Leitung Technikteam MRA Kongresse
m: +43 680 5502283
e: thomas.vollmann@mra.at<mailto:thomas.vollmann@mra.at>
e: technik@mra.at<mailto:technik@mra.at>
www.mra.at<http://www.mra.at/>
[facebook icon]<https://www.facebook.com/CodeTwo> /wirzaubern<https://www.facebook.com/wirzaubern/>







Von: Stefan Frömken <notifications@github.com>
Gesendet: Montag, 2. Dezember 2019 11:09
An: jweiland-net/events2 <events2@noreply.github.com>
Cc: Thomas Vollmann | Kreativ Praxis <thomas.vollmann@kreativ-praxis.at>; Mention <mention@noreply.github.com>
Betreff: Re: [jweiland-net/events2] Wiederholende Veranstaltungen - Listenansicht teilweise ohne Datum (#144)


Hallo @thomasvollmann<https://github.com/thomasvollmann>

hast Du die Templates von der events2 überschrieben? Da sind in den letzten Versionen einige Änderungen hinzugekommen. Evtl. nochmal abgleichen, ob die Struktur noch passt. Bitte auch die Upgrade-Section in der Dokumentation mal checken. Da steht drin, welche Änderungen an den Templates nach nem Upgrade durchzuführen sind.

Kontaktiere mich mal auf Slack. Evtl. kannst Du mir auch nen BE-Zugang bauen, damit ich mir das mal anschauen kann.

Da ich keinen Bindestrich sehe, handelt es sich bei Dir nicht um eine Duration und auch keinen wiederkehrenden gemergten Termin. Somit bleibt nur noch das Datum aus {day.day} übrig. Geh mal bitte in die Tabelle tx_events2_domain_model_day. Sortiere mal nach der Spalte day, hier müssen alle Felder gefüllt sein. Passt das? Wenn ja, dann mach mal ein <f:debug> auf {day}. Ist day dort gefüllt?

Stefan

**Comment by froemken** [comment]
Hallo @thomasvollmann 

argh...warum postest Du die Zugangsdaten denn hier ÖFFENTLICH für jeden bei GitHub!!! Himmel hilf. Bitte lösch das da raus und schick mir die Daten per Slack oder Mail. `Bzgl der Zugangsdaten gehe ich davon aus, dass ich mich verlassen kann` --> Ich werd da schon keinen Quatsch machen...aber dadurch, dass das öffentlich ist, kann wer sonst noch dort Mist anstellen.

Stefan

**Comment by froemken** [comment]
Hallo @thomasvollmann 

ich habe soeben Deine Webseite besucht :-)
2 Dinge zum Termin "ZOOM Magic" mit der UID 41:
- Warum aktivierst Du "Same Day", obwohl die Veranstaltung nur einmal am Tag stattfindet?
- Du hast hier einen wiederkehrenden Termin angelegt, aber weder eine Checkbox für Recurring (1st-5th) als auch keine Checkbox für Weekday (Mo-Su) angegeben. Ohne eine Angebe, kann auch kein Tagesdatensatz generiert werden und ohne Tagesdatenstz kann kein Datum ausgegeben werden.

Schönen Start ins neue Jahr

Stefan

**Comment by thomasvollmann** [comment]
Servus!

DANKE für dein Feedback und die vielen Updates!

Ich habe mit einem Kollegen jetzt einiges getestet und wir haben festgestellt, dass das immer nur Termine im März betrifft.
Wenn ich für die Veranstaltung im Datum auf April oder Dez setzte, wird der Termin korrekt angezeigt.

Unsere Vermutung wäre, dass das die deutsche/englische Schreibweise (das Umlaut ä) betrifft?

Kann ich die EXT so konfigurieren, dass immer die deutsche Variante des Namen genommen wird? (Und auch „Beginn“ anstelle von „Time Begin“)

DANKE für das Feedback!

Von: Stefan Frömken <notifications@github.com>
Gesendet: Freitag, 3. Januar 2020 09:42
An: jweiland-net/events2 <events2@noreply.github.com>
Cc: Thomas Vollmann | Kreativ Praxis <thomas.vollmann@kreativ-praxis.at>; Mention <mention@noreply.github.com>
Betreff: Re: [jweiland-net/events2] Wiederholende Veranstaltungen - Listenansicht teilweise ohne Datum (#144)


Hallo @thomasvollmann<https://github.com/thomasvollmann>

ich habe soeben Deine Webseite besucht :-)
2 Dinge zum Termin "ZOOM Magic" mit der UID 41:

  *   Warum aktivierst Du "Same Day", obwohl die Veranstaltung nur einmal am Tag stattfindet?
  *   Du hast hier einen wiederkehrenden Termin angelegt, aber weder eine Checkbox für Recurring (1st-5th) als auch keine Checkbox für Weekday (Mo-Su) angegeben. Ohne eine Angebe, kann auch kein Tagesdatensatz generiert werden und ohne Tagesdatenstz kann kein Datum ausgegeben werden.

Schönen Start ins neue Jahr

Stefan
