### ISSUE TITLE
Weiterblättern auf weitere Seiten geht nicht

### ISSUE THREAD

**Issue by thomasvollmann** [jweiland-net/events2#145]
Bei mehrseitigen Listen ruft ein Klick auf eine Seitennummer zwar die URL auf, aber der Inhalt wird nicht angezeigt.
![image](https://user-images.githubusercontent.com/55806469/67517585-31f8c580-f6a3-11e9-8757-8276ab751a88.png)

Erst ein manuelles betätigen von STRG + F5 läd den Inhalt der jeweiligen Unterseite.

Auf mehreren Clients und Browsern getestet

**Comment by Hobokens** [comment]
I can't confirm this issue. I can easily navigate between the subpages. (TYPO3 9.5.11; events2 3.9.2)

**Comment by froemken** [comment]
Hallo @thomasvollmann 

ich habe auf meinem Testsystem nun sämtliche Variationen ausprobiert. Ja, ich habe sogar die Cookies für die Webseite komplett verboten und trotzdem klappt die Seitennavigation. Die `news` z.B. hat einen sehr ähnlichen Paginator. Klappt dieser denn auf Deiner Webseite. Magst Du mir mal einen Link Deiner Seite zukommen lassen? Hast Du das Template für das Seiten-Navigations-Widget überschrieben? Existiert bei Dir die Tabelle fe_session. Sind alle Spalten in Database Compare vorhanden?

Du merkst, das Debugging gestaltet sich schwierig. Im Zweifel kannst Du mich auch per Slack kontaktieren und mir mal nen BE-Zugang einrichten. Evtl. klärt sich das Thema dann etwas schneller.

LG

Stefan

**Comment by thomasvollmann** [comment]
nach Update auf die letzte Version klappt es ;)
Was es auch immer war.. ,)

DANKE für die Mühe! lg
