### ISSUE TITLE
Fehler "cHash empty"

### ISSUE THREAD

**Issue by jacques2017** [jweiland-net/events2#15]
Hallo, 
bei der Suche und bei Benutzen des Filters bekomme ich immer den Fehler "Page not found" Reason: Request parameters could not be validated (&cHash empty) 
Kann ich das irgendwo einstellen? 
Ich benutze TYPO3 8.7

Gruß
Jens

**Comment by froemken** [comment]
You're using the TER version, right?
I'm sure I have solved it on current master already:

https://github.com/jweiland-net/events2/blob/master/Configuration/TypoScript/General/setup.txt#L103-L110

Stefan

**Comment by froemken** [comment]
Ich hab im TER gerade mal die events2 2.1.0 released. Sollte gleich verfügbar sein. Probier es mal damit.

**Comment by jacques2017** [comment]
Danke, aber leider funktioniert es trotzdem nicht.
Hatte auch versuchte, das Typoscript einfach mit ins Haupttemplate zu setzen. Hat aber auch nichts gebracht.
Cache ist gelöscht, auch über Install-Tool.

Jens

**Comment by froemken** [comment]
Kann ich nicht nachvollziehen. Wir gehen in den nächsten 2 Tagen mit ner großen Webseite und dieser Extension live und dort funktioniert es. Kann Dir natürlich jetzt nicht den Link zur Testumgebung schicken ;-)
Magst Du mir mal Deine URL nach der Suche mit oder ohne Domain schicken? Da sollte ein:

tx_events2_events%5Baction%5D=listSearchResults

drin stehen.

Probier auch mal folgende Zeile im TS:

plugin.tx_events2.features.requireCHashArgumentForActionArguments = 0

**Comment by jacques2017** [comment]
Danke, die TS-Zeile hat es gebracht.
Der Filter funktioniert.
Bei der Suche habe ich noch das Problem, dass keine Suchergebnisse angezeigt werden. Auch kein Text wie "keine Veranstaltungen gefunden", sondern nur wieder die Suchmaske. Denke aber, das ist nur eine Konfigurationssache.

**Comment by froemken** [comment]
Du hast aber beide Plugins untereinander auf einer Seite, nech? Such-Plugin oben und dadrunter das Standard-Listen-Plugin. Das Such-Plugin selbst hat keine Ergebnisliste.

**Comment by jacques2017** [comment]
Habe ich inzwischen selbst raus gefunden. Hatte das Such.Plugin vorher auf einer anderen Seite...
Es wäre schön (für andere), wenn die Anleitung etwas detaillierter wäre. Auch im Hinblick auf die map-Extension. Aber das wird hier langsam off-topic.

**Comment by froemken** [comment]
Du hast mir heute eine Mail geschickt von meiner Seite aus und dabei eine falsche E-Mail-Adresse angegeben. Bitte nochmal mit korrekter E-Mail-Adresse versuchen, weil ich Dir sonst nicht antworten kann.

**Comment by froemken** [comment]
In der nächsten Version haben wir das Feature komplett deaktiviert. requireCHashArgumentForActionArguments = 0
