### ISSUE TITLE
event wird im kalender nicht angezeigt

### ISSUE THREAD

**Issue by joka123** [jweiland-net/events2#150]
events die mehr als 6 monate in der zukunft liegen werden im kalender nicht angezeigt in der listendarstellung tauchen sie auf.

![kalender_events2](https://user-images.githubusercontent.com/4410271/69564039-8a78f680-0fb2-11ea-843c-4d7dc8d49da9.png)

**Comment by Hobokens** [comment]
I can't confirm this issue. For example, I see events that are 8 months in the future.

**Comment by joka123** [comment]
sorry, your right. i overlooked the settings in the extension configuration.
