### ISSUE TITLE
Fehler in Suchfunktion Veranstalter

### ISSUE THREAD

**Issue by coffermann** [jweiland-net/events2#151]
Wenn man hier einen Veranstalter auswählt  = Funktioniert ordnungsgemäß -
Klickt man dann in dem Dropdown (Veranstalter) auf das weiße Feld im Dropdown erscheint dieine Fehlermeldung.

**Comment by froemken** [comment]
Hallo @coffermann 

habe ich jetzt zwar nicht getestet, aber ich weiß, dass leere Werte oder 0 im Extbase Kontext gerne mal Probleme verursachen. Im Zweifel muss ich solche Werte noch vor Ausführung der Controller-Action selbst rausschmeißen.

Ich kann mir das Problem leider erst nächstes Jahr anschauen.

Stefan

**Comment by froemken** [comment]
Hallo @coffermann 

ich habe den Fehler gefunden. Da war ich etwas extrem mit dem strict types von PHP. Neue Version 4.0.2 habe ich gerade hochgeladen.

Stefan
