### ISSUE TITLE
Beispielkonfiguration für URL in Suche (solr Extension)

### ISSUE THREAD

**Issue by hannesbochmann** [jweiland-net/events2#153]
Gibt es eine Beispielkonfiguration für die URL, welche in der Suche mit der solr Extension generiert wird? Die Herausforderung scheint zu sein, den timestamp Parameter korrekt zu setzen. Bisher verwenden wir das folgende. Das Problem ist aber, dass im timestamp Parameter die Uhrzeit nicht beachtet wird. Das führt zu unterschiedlichen URLs in den Plugins und den Suchergebnissen, was wiederum zu Duplicate Content führt.

Beispiel TypoScript Konfiguration:
```
url = TEXT
url {
    typolink {
        parameter = 123
        additionalParams = &tx_events2_events[controller]=Day&tx_events2_events[action]=show&tx_events2_events[event]={field:uid}&tx_events2_events[timestamp]={field:event_begin}&L={field:__solr_index_language}
        additionalParams.insertData = 1
        returnLast = url
        useCacheHash = 1
    }
}
```

**Comment by froemken** [comment]
Hello @hannesbochmann 

that's correct. For our customers we have set timestamp to 0, too. That way events2 will show the next valid timestamp automatically.

Events2 works with a timeframe (-3 month until +6 months by default) which should be updated each day with help of scheduler task. How to check, if timestamp is still valid? How to remove old entries from Solr Index automatically? How to update all Event2 entries in Solr Index with each scheduler run? In Solr you only have one entry for an event record, but in case of recurring events you need the information which of all these 100 timestamps should be used for output? And maybe they should be sorted by the correct timestamp in result list? Further there are customers, who don't want past event records in search results.

Sorry, that's a little bit too hardcore. We have tried it, but then you got nitpicking from here, there and from whereever else.

Please tell Google to not index the search results. Maybe robots.txt?

Maybe you have time. Try it on your own and use the hooks of Solr and modify the URI before sending it to Solr Index.

In short: We know the problem, but it was too expensive to solve it 100%.

Stefan

**Comment by hannesbochmann** [comment]
Thanks for the fast reply. One thing is still in question. How can past events be removed from the search index? We do the following:

- run the scheduler job to create/update days
- later run a scheduler job to reindex all events every night
- set the following additionalWhereClause in the TypoScript configuration: event_end >= DATE_FORMAT(now(), '%Y%m%d') || (event_end = 0 AND event_begin >= DATE_FORMAT(now(), '%Y%m%d'))

Is this sufficient?

**Comment by froemken** [comment]
Warum habe ich eigentlich in englisch geantwortet ;-) Egal

Eigentlich brauchst Du da nix zusätzlich für zu tun. Schau Dir mal den IndexerHook an. Der wird automatisch geladen, wenn EXT:solr aktiv ist im ExtensionManager.

Da steht auch im Kommentar drin, dass hier Datensätze gelöscht werden, wenn kein nächster Termin generiert werden konnte. Von daher: Bitte mal prüfen.

Evtl. hat sich ja auch Solr geändert und den Hook entfernt. Ich verfolge nicht jedes Update von EXT:solr.

Stefan

**Comment by hannesbochmann** [comment]
:-D
Ja, den Hook habe ich schon gesehen, aber wieder vergessen. ^^ Umso besser wenn man sich nicht explizit darum kümmern muss.
Danke für die schnelle Hilfe.
