### ISSUE TITLE
Default Template für Suche optimieren

### ISSUE THREAD

**Issue by hannesbochmann** [jweiland-net/events2#156]
Im default Template für die Suche wird aktuell der no_cache Parameter gesetzt und für eine korrekte Funktion benötigt. Das ist Bad Practice. In einer sauberen TYPO3 Konfiguration sollte der no_cache Parameter deaktiviert sein, um DoS Angriffe damit nicht zu ermöglichen. Besonders für eine so neue Extension und auch da die Action für die Suche ohnehin USER_INT ist. Daher schlage ich vor, das Template wie folgt zu ändern, damit ein korrekter Link inkl. cHash generiert wird und no_cache entfallen kann.
```
<html
	xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	data-namespace-typo3-fluid="true"
>
<f:layout name="Search" />

<f:section name="main">
	<f:flashMessages />

	<form id="events2SearchForm" class="form-horizontal" method="post" name="search" action="{f:uri.action(action : 'listSearchResults', controller : 'Event')}">
		<f:render partial="Search/FormFields" arguments="{_all}" />
		<div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
				<input type="submit" class="btn btn-default" value="{f:translate(key: 'search')}" />
			</div>
		</div>
	</form>
</f:section>
</html>

```

Noch besser wäre vermutlich komplett die f:form Viewhelper zu verwenden. Dazu sind aber mehr Anpassungen notwendig.

**Comment by froemken** [comment]
Hallo @hannesbochmann 

ich habe das mit dem no_cache Parameter damals nicht drin gehabt und es gab daraufhin insgesamt 3 Tickets, weil die Suche nicht wie erwartet funktionierte. Die Kunden haben eine Suche gestartet und danach eine weitere Suche ausgeführt, was dazu führte, dass sie das gleiche Ergebnis der ersten Suche erhalten haben. Seitdem verwende ich den cHash bei dieser Suche nicht mehr.

Die URI eines Suchformulars mit POST ist nicht kopierbar. Viele kopieren die URI in Foren, Slack oder Ähnlichem, um auf ein ganz bestimmtes ResultSet zu verlinken. Ein weiterer Grund warum ich den cHash nicht verwenden kann.

Wenn ich f:form in Verbindung mit GET verwende, dann werden alle hidden INPUTs mit in die URI gepackt. Inklusive dieser ganzen serialisierten Formularfelder. Das sieht schäbig aus. Einige Browser unterstützen nur ein paar 1000 Zeichen in der URI. Damit diese durch die ganzen Formularfelder nicht abgeschnitten wird, musste ich mich für das FORM-Tag entscheiden.

Das Select Feld für die Unterkategorien wird dynamisch mittels JavaScript befüllt und ist nur sichtbar, wenn eine Hauptkategorie ausgewählt wurde. Dies führte zu Problemen im PropertyMapper. Klar kann ich den PropertyMapper konfigurieren, aber andere Kunden wollen die Unterkategorien nicht haben.

**Comment by hannesbochmann** [comment]
@froemken 
Danke für die Erläuterung. Vielleicht könnte ja dazu was in die Dokumentation, um beide Möglichkeiten (mit GET und no_cache und mit POST und cHash) zu beschreiben mit Vor- und Nachteilen.

**Comment by froemken** [comment]
Ich habe einen neuen Bereich "FAQ" in die Dokumentation mit aufgenommen. Heute oder Morgen kommt die neue Version dann raus.
