### ISSUE TITLE
Make upload folder configurable

### ISSUE THREAD

**Issue by benwalch** [jweiland-net/events2#157]
Thanks alot for this great extension!

It would be awesome if the target upload folder defined hardcoded in
https://github.com/jweiland-net/events2/blob/master/Classes/Property/TypeConverter/UploadMultipleFilesConverter.php#L191 could be configured, e.g. with TypoScript

**Comment by benwalch** [comment]
made a PR for that

**Comment by froemken** [comment]
Hello @benwalch 

I have commented your issue within the PR.

I will release a new version within this week.

Stefan
