### ISSUE TITLE
Route enhancer does not replace special chars in title

### ISSUE THREAD

**Issue by darthnorman** [jweiland-net/events2#158]
We are using the route enhancer from https://github.com/jweiland-net/events2/blob/4d5131338f44f6193593e225480f7250a53e8f60/Classes/Routing/Aspect/TimestampMapper.php#L23
```
* routeEnhancers:
 *   Events2ShowPlugin:
 *     type: Extbase
 *     extension: Events2
 *     plugin: Events
 *     routes:
 *       -
 *         routePath: '/show/{date}/{event_title}'
 *         _controller: 'Day::show'
 *         _arguments:
 *           date: timestamp
 *           event_title: event
 *     requirements:
 *       date: '\d+'
 *       event_title: '^[a-zA-Z0-9]+\-[0-9]+$'
 *     defaultController: 'Day::show'
 *     aspects:
 *       date:
 *         type: TimestampMapper
 *         format: 'Y-m-d_Hi'
 *       event_title:
 *         type: PersistedPatternMapper
 *         tableName: 'tx_events2_domain_model_event'
 *         routeFieldPattern: '^(?P<title>.+)-(?P<uid>\d+)$'
 *         routeFieldResult: '{title}-{uid}'
```
Problem is that the title field is used without any replacement of spaces, quotes, brackets etc.
Example:
Event Title: Ausstellung "Far(r)baholics"
Path segement: /Ausstellung "Far(r)baholics"-40

I've looked around and found this forge bug, looks like its exaclty the same problem: https://forge.typo3.org/issues/86797

Do you have a working setup to get around this behaviour and to actually have nice URLs?

**Comment by froemken** [comment]
OMG, that's really nasty. I have just implemented the column slug_segment like in EXT:news. I have updated my example in TimestampAspect.

Thank you for your report.

Events2 4.1.0 is now available with composer. In a few minutes it will be available in TER, too.

Stefan
