### ISSUE TITLE
Upgrade wizard for new slug field

### ISSUE THREAD

**Issue by darthnorman** [jweiland-net/events2#160]
Since you added the new slug field (thanks for that, again!) it is impossible to update to the new extensions, because there's no upgrade wizard to fill the field for existing events. We'd have to manually create the slug in each event.
Would you recommend https://extensions.typo3.org/extension/slug to do so?

**Comment by froemken** [comment]
Damn. Right. I'm just on another project. I will repair that afterwards.

**Comment by froemken** [comment]
I have just released version 4.1.1 where I have added the missing SlugUpdater for InstallTool.
