### ISSUE TITLE
provide setter for sys_language_uid

### ISSUE THREAD

**Issue by benwalch** [jweiland-net/events2#161]
Currently, it is not possible to set the language of a created event through the frontend, since the Event model has no property to set the sys_language_uid. 
Please provide a setter for the language (internal `_languageUid`) like it is done in ext:news: https://github.com/georgringer/news/blob/master/Classes/Domain/Model/News.php#L1160

**Comment by froemken** [comment]
I have just created a new Trait to add TYPO3 Columns to all Domain Models:
https://github.com/jweiland-net/events2/pull/162

It will be available with next Release

**Comment by benwalch** [comment]
Hi, thank you for the quick response and the attention to this issue. The trait is very nice, but it does not work for the sys_language_uid. The language of created events through FE is not respected. This is the case, because Extbase handles the language property internally with `_languageUid` in domain model. Could you please adjust your trait?

**Comment by froemken** [comment]
I have adjusted the trait. I will release a new version today or tomorrow.
