### ISSUE TITLE
Field 'path_segment' (Slug) is not set when creating an event through FE

### ISSUE THREAD

**Issue by benwalch** [jweiland-net/events2#166]
When creating an event through FE, the path_segment field is not set.

**Comment by froemken** [comment]
Hello @benwalch 

I just have released version 6.2.0 of events2 which has this missing feature included:
https://github.com/jweiland-net/events2/pull/251

Info: By default we will not generate any path_segment. Please visit Extension Settings and configure them as you like.

Stefan
