### ISSUE TITLE
misconfiguration in path_segment and updater class

### ISSUE THREAD

**Issue by SvenJuergens** [jweiland-net/events2#172]
Hi Stefan,

first, cool extension :)

If you make an update and run the updater for path_segment. you get nice slugs according to the format: ['title' ](https://github.com/jweiland-net/events2/blob/21d4791a809854ee179314148a3158c572eda182/Classes/Updater/EventsSlugUpdater.php#L135)
But if you edit an event and update the slug there you get a format like ['title - uid' ](https://github.com/jweiland-net/events2/blob/21d4791a809854ee179314148a3158c572eda182/Configuration/TCA/Overrides/tx_events2_domain_model_event.php#L38)* 
Could you standardize this? I would be for a format like 'title' without extra UID, or is there something against it?

best regards
Sven

**Comment by froemken** [comment]
Hello @SvenJuergens 

thank you for that hint. I have just released version 4.2.1 which solves that issue. Further it should speed up UpgradeWizard generating slugs.

Stefan
