### ISSUE TITLE
JavaScript error: Cannot read property 'subCategory'

### ISSUE THREAD

**Issue by esokoll2** [jweiland-net/events2#177]
Under certain circumstances the search plugin creates errors:
`Uncaught TypeError: Cannot read property 'subCategory' of undefined at Object.Events2.fillSubCategories (Events2.js?1582547181:315)...`
Then the "SubCategory" field does not work.

**Comment by froemken** [comment]
Hello @esokoll2 

thank you for your help. I will release a new version today, where I process each Events2 Plugin individuell in JavaScript.

Stefan
