### ISSUE TITLE
Filter for organizers not shown

### ISSUE THREAD

**Issue by wowawebdesign** [jweiland-net/events2#184]
If I activate the option "Show a filter selection for organizers in Frontend" in a plugin, no selectbox is visible in the frontend.

In the partial EXT:events2/Resources/Private/Partials/Event/Filter.html the array organizers is empty.

I tried to set the organizer as requirement in the extension configuration, but this had no effect.

**Comment by froemken** [comment]
Hello @wowawebdesign 

I have just tested it and it works.
Please remember that this selectbox will only be visible if you have created more than 1 Organizer. Further the Checkbox `hide_in_filter` in Organizer record has to be deactivated.

Further, many integrators creates additional sysfolders for events, locations and organizers. Can you please check, if you have defined all theses StorageFolder UIDs in Plugin or plugin.tx_events.persistence.storagePid.

If you still have this problem, re-open this ticket with further information.

Have a nice and looong weekend

Stefan

**Comment by wowawebdesign** [comment]
Ok, the problem was actually that I had created the organizers in a separate folder. When I added that one in the plugin as well, it worked.
