### ISSUE TITLE
Feature request: Global exceptions (like holidays, e.g.) 

### ISSUE THREAD

**Issue by ceekay73** [jweiland-net/events2#185]
It would be very userful to have the possibility to create exceptions globaly - to pause all affected events in timeframe (simliar to what was possible in calendar_base).

Thanks for the great event2 extension by the way.
Kind regards

**Comment by froemken** [comment]
Hello @ceekay73 

wow...that will be hard. Do you want to create a kind of blocked date in general or more a defined blocked timeslot like 10:00-13:00 for a day?

Stefan

**Comment by ceekay73** [comment]
Hm, in my case in a project the question of handling holidays came up (like easter or so  - no events in that pereod). At the moment we would have to set exceptions for that in each event. Depending on the amount of events, this is not realy possible. 

So sometihng like before displaying events check if there is a defined pause-event in that timeframe and if there is, don't display it wolud be one way of approaching it i think.

regards,
Christoph

**Comment by froemken** [comment]
Good Morning,

we never had this issue. I'm sure: Implementing that will take years. There are other ideas which have a higher priority. I have an idea. I can implement a SignalSlot just after all day records are generated in DayGenerator. That way you can hook in, and remove all date records which does not expect your behavior. Would that be a solution for you?

Stefan

**Comment by ceekay73** [comment]
Yes, signal slots wolud be good.
Christoph

**Comment by froemken** [comment]
Good Morning @ceekay73 

I just have pushed version 5.1.0 to packagist.
Please use SignalSlot `postGenerateDays` in DayGenerator. I have added the current event and the complete DayGenarator. You can access the days over `$dyGenerator->dateTimeStorage`

Hope it helps. Have a good start into the new week

Stefan
