### ISSUE TITLE
Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/events2#187]
Error during installation or database compare.

Quick solution: add ROW_FORMAT=DYNAMIC to the SQL-Query to create the tabel tx_events2_domain_model_event

Database collation: utf8mb4_unicode_ci

**Comment by froemken** [comment]
Moin @wowaTYPO3 

I have solved this issue with release 5.1.1

Thank you for your support

Stefan
