### ISSUE TITLE
Compatibility to TYPO3 v.10

### ISSUE THREAD

**Issue by t3korvin** [jweiland-net/events2#189]
Is there any chance that the extension would be compatible with TYPO3 v.10 sometime?

**Comment by froemken** [comment]
Good Morning @t3korvin 

yes of cause. As events2 is not a small extension anymore, it will take same time to update this extension. We are lucky, that one of our customers needs an Update of events2, too, and yes we get the order to do so. Yeah.
We are currently in the planning phase and will start upgrading his project within the next month. Maybe events2 is one of the first extensions to upgrade. In that case we may release a new version within the next 2 or 3 month.

Stay tune

Stefan

**Comment by froemken** [comment]
Version 6.0.0 is now registered at Packagist. 
TER upload within the next week
