### ISSUE TITLE
Use PageTitle-API 

### ISSUE THREAD

**Issue by netthinks** [jweiland-net/events2#191]
The TypoScript option config.titleTagFunction has been marked as deprecated and will be removed with TYPO3 v10.

**Comment by froemken** [comment]
Hello @netthinks 

I'm just working on a TYPO3 9 and 10 release of events2. With version 6.0.0 it will be possible to create dynamic page-titles with TypoScript that way:

```
   config.pageTitleProviders {
     events2 {
       provider = JWeiland\Events2\PageTitleProvider\Events2PageTitleProvider
       # Please add these providers, to be safe loading events2 provider before these two.
       before = record, seo
     }
   }
```

Have a nice warm start into the weekend

Stefan
