### ISSUE TITLE
Position of field `import_id` is strange

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#193]
IMO the field `import_id` doesn't belong to the media tab but some different one (also access feels wrong)

maybe hide it by tsconfig and if needed visible, people need to set tsconfig value to 0?

**Comment by froemken** [comment]
Hi Georg,

as the field is only relevant for DB and Migration Specialists we will remove that field from TCEFORM (type=passthrough) with next Bugfix-Release

Stefan

**Comment by froemken** [comment]
Hi @georgringer 

I have set this "internal" field to passthrough. If anybody need the value of this field he should look into DB directly.

Stefan
