### ISSUE TITLE
Geocoordinates for location

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#194]
The location should have coordinates - would be cool to have some copy paste code from https://github.com/jweiland-net/maps2 (or maybe we should extract code from there into custom extension and reuse the whole backend stuff)

**Comment by froemken** [comment]
Hello @georgringer 

no need to do so. events2 come with a pre-configuration for our new Maps2 API. Have a look into TCA/Overrides/tx_events2_domain_model_location.php.
If maps2 is loaded a new column "tx_maps2_uid" will automatically added to location table incl. a TCA reference. Further, with each location save, we automatically create a new PoiCollection record and assign it to location record.

If you need more information about Maps2 API you can have a look here: https://docs.typo3.org/p/jweiland/maps2/9.2/en-us/DeveloperManual/Api/Index.html

Stefan
