### ISSUE TITLE
Argument 1 passed to JWeiland\Events2\Converter\TimeToStringConverter::convert() must be of the type int, string given

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#197]
If a simple event is created with a time `duration` set to `2` instead of `2:00`, the backend breaks with

```
Argument 1 passed to JWeiland\Events2\Converter\TimeToStringConverter::convert() must be of the type int, string given
```

**Comment by froemken** [comment]
Hi Georg,

interesting, I have added a special TimeType to TCA to check that before saving. Hmm. Needs a closer look into the code.

Thank you for that hint.

Stefan

**Comment by froemken** [comment]
Hi @georgringer 

I have found and solved the problem. Thank you for that hint.

But I like the approach to just enter an integer like 4 and expect an automatically conversion to 04:00. I have implemented that as new feature. Thank you.

Stefan
