### ISSUE TITLE
typo in "informations"

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#198]
in english it is called `information`. in the long run I would like to change the DB field but as start pls change the xlf label + add a 2nd getter in the model and use that in the templates

**Comment by froemken** [comment]
Thank you Georg,

I know that issue since 3 or 4 years.

It's a good hint to add a further Getter for Information. Should be possible for next Bugfix-Release.
Within this year a bigger Release is planned. Hopefully we will add this feature (DB) with version 7.0.0.

Stefan

**Comment by froemken** [comment]
Please clear System Cache, as I have added a Mapping for detailInformation to detail_ informations in ext_typoscript_setup.txt and Extbase/Classes.php
