### ISSUE TITLE
Provide more helpful Readme.rst

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#199]
It would be cool to have a nicer readme.rst (or md file) for github including:

all those nice icons which are out there

- status of tests + coverage
- main version

+ short info, especially the composer require command

**Comment by froemken** [comment]
Hello @georgringer 

I have just pushed an updated version and I have renamed our README.rst into README.md.
No we have a little svg on top which shows the result of last CI.

Thank you for that hint

Stefan
