### ISSUE TITLE
IndexerHook shouldn't unset documents

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#200]
The `IndexerHook` shouldn't unset the document as this leads to the problem that any hook after the one from events2 doesn't get any document anymore.

if there should some documents not be shown, do that in the search IMO

**Comment by froemken** [comment]
Hi @georgringer 

currently I don't know how to solve that without breaking many of our customers websites. They don't want to see any old documents in Solr results. If I remove that hook, old event records will be indexed where no nextDate can be calculated for. Removing them while loading the search results is a problem, too. The paginator will show: "Show records 1-15 of 328", but in result you will only see 4 or 5 records. So "sodom or gomorrah". Removing in Search Results is a visible problem for the customer. Removing documents while Indexing is invisible, but results in a problem for other programmers. We decided for a more customer friendly solution. Sorry.

Of cause we are always happy to hear about a much better solution for that.

Stefan

**Comment by georgringer** [comment]
ok will close that I guess
