### ISSUE TITLE
EventController::sendMail must check if setTo/from is set

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#206]
Currently there is no check if the from/to email address is set or not
```php
        $this->mail->setFrom($this->extConf->getEmailFromAddress(), $this->extConf->getEmailFromName());
        $this->mail->setTo($this->extConf->getEmailToAddress(), $this->extConf->getEmailToName());
```

this will lead to the error `Email "" does not comply with addr-spec of RFC 2822.`

I suggest to validate those basic stuff and don't even allow creating an event if not set

**Comment by froemken** [comment]
Hello @georgringer 

I can't reproduce this error, as I have a check for that in ExtConf:
https://github.com/jweiland-net/events2/blob/master/Classes/Configuration/ExtConf.php#L181

Can you please add some information how I can reproduce this issue?

Thank you

Stefan

**Comment by georgringer** [comment]
using different approach, didn't check anymore therefore, code looks good
