### ISSUE TITLE
Avoid using ObjectManager if not needed

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#211]
If there is no real need for using extbase models or repositories, the usage of the `ObjectManager` should be avoided.

**Example `\JWeiland\Events2\Configuration\ExtConf`:** 

No extbase used. this means if this class is used it should be injected either by constructor injection, or makeInstance directly (in controller context just use `initializeAction` 

**Example `\JWeiland\Events2\Service\EventService`**

This classes must currently be called by the ObjectManager to resolve propties via inject methods. However most of those don't use extbase at all:

- `extConf`: see above
- `dateTImeUtility`: not using extbase at all
- `eventRepository`: just basic repository stuff > migrate it to direct DB calls

**Example  `\JWeiland\Events2\ViewHelpers\FeUserViewHelper`**

Just fetch the data directly from `UserRepository`, no extbase involved, no ObjectManager needed at all

**Comment by froemken** [comment]
Hello @georgringer 

damn that was much work to do. Nearly 1200 changed lines and 600 new lines of code: https://github.com/jweiland-net/events2/pull/212

Hopefully everything is still working ;-)

Stefan
