### ISSUE TITLE
Update von 1.4.1 nach 2.0 bzw. 2.1

### ISSUE THREAD

**Issue by tcmueller** [jweiland-net/events2#22]
Ich habe Events2 1.4.1 unter TYPO3 7.6.27 laufen. Nach einem Update über den Extension-Manager aus 2.0, dem erfolgreichen ausführen des Aktualisierungsscriptes im Extension-Manager und dem erneuten einbinden des Templates wird im Frontend nur der Hinweis angezeigt "Heute keine Veranstaltungen"!
In den Settings wurden alle Einstellungen der Version 1.4.1 übernommen. Habe das Ganze jetzt mehrmals durchgespielt und bin mit meinem Latein am Ende. Irgendein Tipp woran es liegen könnte?

**Comment by froemken** [comment]
Hallo @tcmueller 

früher konnte mittels Checkbox zwischen Single und Multiple Veranstaltungen gewechselt werden. In der 2er Version kam ein weiterer Veranstaltungstyp hinzu, weshalb ich die Spalte event_type hinzugefügt habe. Bitte schau mal in der Datenbank, ob dieses Feld für jede Veranstaltung gefüllt ist.

Lieben Gruß

Stefan

**Comment by tcmueller** [comment]
Ja, in jedem Datensatz steht entweder "single" oder "recurring"

**Comment by froemken** [comment]
Leg bitte den "Regenerate Days" scheduler Task an und führe den einmal aus. Dieser Task sollte eh jeden Tag mindestens einmal aufgerufen werden.

**Comment by tcmueller** [comment]
Danke!!! Jetzt funktioniert es wieder einwandfrei!

**Comment by froemken** [comment]
Oh...sehe gerade...genau den Punkt habe ich vergessen hier noch mit aufzuführen: https://docs.typo3.org/typo3cms/extensions/events2/2.2.5/AdministratorManual/Update/Index.html

Viel Spaß mit der Events2
