### ISSUE TITLE
Simplify timestamp argument generation for links

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#220]
Currently this code is used:
```html
<f:link.action
			action="show"
			controller="Day"
			pageUid="{settings.pidOfDetailPage}"
			arguments="{timestamp: '{day.dayTime->f:format.date(format: \'U\')}', event: day.event}"
			title="{f:translate(key: 'singleView')}: {day.event.title}"
		>{f:translate(key: 'showDetailview')}</f:link.action>
```

I propose a getter in the `Day` object which returns the timestamp. so that code would be then

```html
<f:link.action
			action="show"
			controller="Day"
			pageUid="{settings.pidOfDetailPage}"
			arguments="{timestamp: day.timestamp, event: day.event}"
			title="{f:translate(key: 'singleView')}: {day.event.title}"
		>{f:translate(key: 'showDetailview')}</f:link.action>
```
Benefits would be:

1. Easier to read and use for all of us
2. Should be a bit faster as one VH less is involved

**Comment by froemken** [comment]
Hello @georgringer 

I have added 3 new helper methods for Fluid for you:

{day.dayTimeAsTimestamp}
{day.sortDayTimeAsTimestamp}
{day.sameDayTimeAsTimestamp}

I have update the two usages in our templates accordingly

Stefan
