### ISSUE TITLE
Make XmlImporter extendable

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#226]
It would be great to have the XmlImporter extendable. This could be solved by using a signal slot (but also requires the xsd to allow one additional field like `additional` which can be filled with all custom stoff or by having a getter on the XmlImport which retrieves a mapping to the events uids, just like the `$this->substNEWwithIDs` within the core's datahandler

**Comment by froemken** [comment]
Griaß di @georgringer 

I will make path to XSD configurable as I explained in the other ticket. I don't think that I will build something like a "merge" for XSD and and own stuff.

Would a SignalSlot at the end of the foreach where the $data and $event is available an option for you? Behind the foreach it may happen that some invalid events are missing.

Stefan

**Comment by georgringer** [comment]
@froemken thanks for your feedback. I would suggest to move the `$this->persistenceManager->persistAll();` into the `processEvent` and add the signal there. this would have the benefit that 3rd party extensions get access to all ids of all relations and do anything.

**Comment by georgringer** [comment]
don'T need that anymore, fixed it myself
