### ISSUE TITLE
Add link to xmlimporter xsd to the manual

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#227]
The faq entry about the XmlImporter should contain a link to the example xml files within the tests. link to should go to the github site as the extension itself might not contain the test files

**Comment by froemken** [comment]
Hi @georgringer 

on Slack it sounds like you will do a PR ;-)

But thank you for that improvement, we will add a sentence or two to the documentation with next public version

Nice greetings

Stefan

**Comment by georgringer** [comment]
Yes can do the pr
