### ISSUE TITLE
Why are organizer/location/categories required in AbstractImporter?

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#228]
Currently `\JWeiland\Events2\Importer\AbstractImporter::isValidEvent` returns false if organizer, location or categories are empty. I don't see a reason for that

**Comment by froemken** [comment]
Hello @georgringer 

thank you for that hint. Yes, you're right. The XSD file we deliver needs categories, organizer and location as this extension was builded for a customer who needs that.
I prefer a solution to make the path to XSD file configurable over Extension Settings.

Stefan

**Comment by georgringer** [comment]
@froemken sorry but is about this code
```php
 // specified organizer exists?
        $organizer = $this->getOrganizer($event['organizer']);
        if (empty($organizer)) {
            $this->addMessage(
                sprintf(
                    'Event: %s - Date: %s - Error: %s',
                    $event['title'],
                    $eventBegin->format('d.m.Y'),
                    'Given organizer "' . $event['organizer'] . '" does not exist in our database'
                ),
                FlashMessage::ERROR
            );
            return false;
        }
```

as a solution I would use `isset()` to check if organizer,categories,... are set and only if true, check if a record can be found

**Comment by froemken** [comment]
Moin @georgringer 

found it, thank you. I just have pushed a new patch which solves that.

Stefan
