### ISSUE TITLE
Don't use FileInterface for import files

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#229]
I propose to change the Importer to remove the restriction to use `FileInterface`. Furtheremore instead of file itself, the file's content should be handed into the importer. I see the following advantages:

- the importer can be used e.g. for importing events by 3rd party extensions
- no real file needs to be created but the e.g. CLI import can just hand into the xml's content
- the logging would be a real logging using the logging framework

**Comment by froemken** [comment]
Moin @georgringer 

thank you for that hint. What do you prefer?

- Abs. Path as string
- Rel. Path as string
- XML file content as string
- SplSimpleXml as object
- plain array (sorry, because of many validation I'll not implement that)

Stefan

**Comment by georgringer** [comment]
I guess the simplexml will would be best

**Comment by froemken** [comment]
Hello @georgringer 

I have tried something, but as all used methods of TYPO3 and PHP needs a string parameter I prefer using XML structure as string. Else I have to convert a XML structure which is not needed for the methods itself.

Stefan

**Comment by georgringer** [comment]
don'T need that anymore, fixed it myself
