### ISSUE TITLE
AbstractImporter shouldn't depend on the Task

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#230]
The AbstractImporter shouldn't have a property `$task`. The `Importer` should use a getter to set the storagePid.

**Comment by froemken** [comment]
Ahoi @georgringer 

this is a pretty good point. I can remove the setTask method from ImporterInterface and implement a setStoragePid method instead.
Shouldn't be as much work.

But for now we have a big project in our timeline. So maybe it will take some time until we can solve that.

Thank you for your support. Great.

Stefan
