### ISSUE TITLE
Description field for location & organizer

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#235]
It would be great to have a RTE field for location & description. thanks a lot!

**Comment by froemken** [comment]
Hello @georgringer 

thank you for this feature request, but currently we will not implement this feature.

Please make use of a SitePackage extension to add these columns to tables `tx_events2_domain_model_location` and `tx_events2_domain_model_organizer` and extend location and /or organizer model with help of EXT:extender.

Have a nice start into this new week

Stefan
