### ISSUE TITLE
Installation brokes under TYPO3 V10

### ISSUE THREAD

**Issue by maslme** [jweiland-net/events2#236]
When I'm trying to install events2 (latest github version) via extension manager it brokes with the error:

Fatal error: Declaration of JWeiland\Events2\Ajax\AbstractAjaxRequest::processAjaxRequest(array $arguments) must be compatible with JWeiland\Events2\Ajax\AjaxInterface::processAjaxRequest(array $arguments): string in [...]/typo3conf/ext/events2/Classes/Ajax/AbstractAjaxRequest.php on line 23

and in the frontend I got:

(1/1) Symfony\Component\DependencyInjection\Exception\InvalidArgumentException

Expected to find class "JWeiland\Events2\Ajax\AbstractAjaxRequest" in file "[...]/typo3conf/ext/events2/Classes/Ajax/AbstractAjaxRequest.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource.

For me I could solve it with changing:
events2/Classes/Ajax/AbstractAjaxRequest.php

add after line 18
use JWeiland\Events2\Ajax\AjaxInterface;

and change line 69 to
abstract public function processAjaxRequest(array $arguments): string;

**Comment by froemken** [comment]
Hello @maslme 

you wrote `trying to install events2 (latest github version)` but in latest version there is no AbstractAjaxRequest:

https://github.com/jweiland-net/events2/tree/master/Classes/Ajax

So IMO you're not using the latest github version (master).

Stefan

**Comment by froemken** [comment]
I remember this issue in August 2020 and I have solved it by removing the AbstractAjaxRequest. Please update to latest master and the problem is solved. I have just tested that on a TYPO3 10.4 standalone (non-composer) system.

**Comment by froemken** [comment]
I have just released version 6.1.0 for packagist and TER. So no need to work with a ZIP of Github anymore
