### ISSUE TITLE
routeEnhancer

### ISSUE THREAD

**Issue by hempelta** [jweiland-net/events2#237]
Can you help me?

I made an update from 9.5.18 to 9.5.22. 

After the update i get the error "Parameter "tx_events2_events__event" for route "tx_events2_events_0" must match"[a-zA-Z0-9]+\-[0-9]+" ("{mySlugPath}" given) to generate a corresponding URL."

I have the following routeEnhancer for Events2ShowPlugin:

routeEnhancers:
  Events2ShowPlugin:
    type: Extbase
    extension: Events2
    plugin: Events
    routes:
      -
        routePath: '/show/{date}/{event_title}'
        _controller: 'Day::show'
        _arguments:
          date: timestamp
          event_title: event
    requirements:
      date: '\d+'
      event_title: '^[a-zA-Z0-9]+\-[0-9]+$'
    defaultController: 'Day::show'
    aspects:
      date:
        type: TimestampMapper
        format: 'Y-m-d_Hi'
      event_title:
        type: PersistedAliasMapper
        tableName: tx_events2_domain_model_event
        routeFieldName: path_segment

**Comment by froemken** [comment]
Hello @hempelta 

please use, as we do not add uid anymore to slug:

`event_title: '^[a-zA-Z0-9]+$'`

Stefan

**Comment by hempelta** [comment]
okay, thx.
I changed it, but now I get the following message:

Parameter "tx_events2_events__timestamp" for route "tx_events2_events_0" must match "\d+" ("2021-01-09_0900" given) to generate a corresponding URL.

**Comment by froemken** [comment]
Hello @hempelta 

please set

date: '\d+-\d+-\d+_\d+'

Stefan

**Comment by hempelta** [comment]
check! thank you. it work's :-)
