### ISSUE TITLE
events2 6.0.0 doesnt work with TYPO3 9.5.2.3

### ISSUE THREAD

**Issue by FurtFan86** [jweiland-net/events2#242]
I get this message:

(1/1) #1476045117 TYPO3\CMS\Extbase\Persistence\Generic\Exception\InvalidClassException
Could not find class definition for name "Event". This could be caused by a mis-spelling of the class name in the class definition.
in /var/www/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapFactory.php line 131

`*/
    protected function buildDataMapInternal($className)
    {
        if (!class_exists($className)) {
            throw new \TYPO3\CMS\Extbase\Persistence\Generic\Exception\InvalidClassException(
                'Could not find class definition for name "' . $className . '". This could be caused by a mis-spelling of the class name in the class definition.',
                1476045117
            );
        }`

With the version 5.1.2 it works

**Comment by froemken** [comment]
This issue is solved since 3 months and will be released with upcoming version 6.1.0.

**Comment by froemken** [comment]
I have just released version 6.1.0 for packagist and TER
