### ISSUE TITLE
Event::getLocationAsString should be part of the location model

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#249]
the method `\JWeiland\Events2\Domain\Model\Event::getLocationAsString` should be moved into the location model because of the following advantages:
- less code because all this `$this->getLocation()` can be replaced with `$this->` and the getter with the property access
- biggest advantage: the getter can be used from every where else where the location model is used

to avoid breaking changes the method should be kept in the `Event` and just call `$this->getLocation->getLocationAsString()`

**Comment by froemken** [comment]
Hi @georgringer 

I have just released version 7.0.13 containing a patch solving your issue.
Thank you for your help

Stefan

**Comment by georgringer** [comment]
awesome, thx
