### ISSUE TITLE
[FEATURE REQUEST] month/year filter

### ISSUE THREAD

**Issue by scoutie78** [jweiland-net/events2#259]
Would it be possible to add a filter that shows the list of events grouped by month/year?

![event_filter](https://user-images.githubusercontent.com/39914394/110624225-35a8c180-819e-11eb-9f4d-25426ccb5c31.jpg)

**Comment by froemken** [comment]
Hello @scoutie78 

thank you for your Feature Request.
Currently I don't think that we will implement such a feature. By default events2 works within a time-frame from -3 month up to +6 month. This is a range of 9 month, but your view needs at least 36 months.
I would prefer that you update our templates to show these years and months and add a click event to our getDaysOfMonth  eID Script. Please insert the calendar plugin and switch between month. Open Browser Console -> Network -> XHR. With each click a new request will be started, to retrieve the days of month. Maybe you see a possibility to adopt that for your view.

Nice greetings

Stefan

**Comment by froemken** [comment]
Please use the various Hooks/Services/EventListeners of events2 to build such a plugin on your own.

I will close this issue for now.

Stefan
