### ISSUE TITLE
Provide key to in hook registration

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#263]
To make it easier to override/remove hooks implemented by events2, a key should be used

**Comment by froemken** [comment]
Hello @georgringer 

just to understand you correct. Do you mean such lines of code:

https://github.com/jweiland-net/events2/blob/master/ext_localconf.php#L113-L115

Stefan

**Comment by georgringer** [comment]
@froemken yes, use either timestamp or something like 
```php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['afterSearch']['ext-events2']
```

**Comment by froemken** [comment]
Good morning @georgringer 

I just have pushed the change to master. You can use new string-based array-keys with upcoming release `6.2.6`

Stefan
