### ISSUE TITLE
Events2 2.2.5: Fehler nach TYPO3-Update 7.6.28 auf 8.7.15

### ISSUE THREAD

**Issue by tcmueller** [jweiland-net/events2#27]
Hallo, ich habe Events2 2.2.5 unter TYPO3 7.6.28 laufen. Nach einem Update auf 8.7.15 bekomme ich folgende Fehlermeldung:

Call to undefined method JWeiland\Events2\Persistence\Typo376\Generic\Storage\Typo3DbBackend::getStatementParts()

Deaktiviere ich im Extensionsmanager Events2, läuft der Rest fehlerfrei.

**Comment by froemken** [comment]
Hallo @tcmueller 

Danke für den Hinweis. Da Extbase kein GROUP BY kann, haben wir das für Extbase nachgeholt. Dazu müssen jedoch ein zwei Dateien von Extbase angepasst werden. Das machen wir mittels der statischen Templates. Je nach TYPO3 Version wird ein anderes TYPO3 spezifisches statisches Template angeboten. Als Du mit TYPO3 7 unterwegs warst, hast Du das statische Template für "events2 (7.6)" im Template eingebunden. Jetzt nach dem Wechsel heißt das Template "events2 (8.7)". 
Demnach musst Du überall dort, wo Du das 7.6 Template eingebunden hattest jetzt das 8.7er Template einbinden.
