### ISSUE TITLE
Errors installing events2 7.01

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#281]
I use TYPO3 10.4.17

Installing the newest versions (7.0.1) I get two errors and the site breaks

`Uncaught TYPO3 Exception: Too few arguments to function JWeiland\Events2\PageTitleProvider\Events2PageTitleProvider::__construct(), 0 passed in /var/www/vhosts//xxxx.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3474 and exactly 1 expected | ArgumentCountError thrown in file /var/www/vhosts/xxxx.jweiland-hosting.de/httpdocs/typo3cms/abc/typo3conf/ext/events2/Classes/PageTitleProvider/Events2PageTitleProvider.php in line 38. Requested URL: https://my-domain.de/404 `

and

` Uncaught TYPO3 Exception: Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\InvalidTag::getType() | Error thrown in file /var/www/vhosts/xxxx.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/vendor/symfony/property-info/Extractor/PhpDocExtractor.php in line 145. Requested URL: https://www.md-domain.de/ `

**Comment by froemken** [comment]
Hello @Hobokens 

thank you for that ticket. I have just released version 7.0.2 for composer.
As I have solved that issue from my privat PC I don't have access to TYPO3 company account of TYPO3 to upload that release to TER.

Stefan

**Comment by Hobokens** [comment]
Hello @froemken 
I just tried to install events2 7.0.3 with ter. I get the error 
`
 Too few arguments to function JWeiland\Events2\Configuration\ExtConf::__construct(), 0 passed in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3505 and exactly 1 expected | ArgumentCountError thrown in file /var/www/vhosts/xxxxx.jweiland-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/events2/Classes/Configuration/ExtConf.php in line 87. `

Regards
Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

where do you get this error? If I search for `makeInstance(ExtConf` I will only find results in my test files. It seems that you call events2 ExtConf from within your own code. Do you have a backtrace for me?

Stefan

**Comment by Hobokens** [comment]
Hi Stefan,
I'm not sure that I understand you right. It's a JWeiland-Installation :-) www.hfm-wuerzburg.de.Maybe you can take a look?
Hobokens

**Comment by froemken** [comment]
@Hobokens 

I have found three installations in two different hosting packages. And in each installation events2 in version 6.2.* is installed. All Logs do not contain any ExtConf error. I tried to call you, but I don't find you at slack and I don't have or found an email address.

Stefan

**Comment by d3werk** [comment]
Hi @froemken
I tried to install events2 7.0.3. I get this error.

Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\InvalidTag::getType()

Regards
d3Werker

**Comment by froemken** [comment]
@d3werk @Hobokens 

OK...I can reproduce the error on a TYPO3 standalone installation. Thank you for your support. There was a makeInstance in TCA Overrides of events2 location:

`$extConf = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\JWeiland\Events2\Configuration\ExtConf::class);`

As I can't use short classnames here I had to use the full qualified classname. That's why I have not found it in my search.

I will release a new version 7.0.4 today.

Stefan

**Comment by froemken** [comment]
@d3werk @Hobokens 

Thank you for supporting me. I just have uploaded events2 in version 7.0.4 to packagist and TER.
In that release I have found some more classes which are not correctly set in Dependency Injection.
