### ISSUE TITLE
jquery-ui-1.12.1

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#283]
Hi,

events2 is including in setup
`jQueryUiForEvents2 = https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js`

I wonder if all the javascript is needed (253 kb) or if the file can't be reduced to the necessary functionalities as it is possible here 
`https://jqueryui.com/`
Then also the call at Google could be renounced.
Regards
Hobokens

**Comment by froemken** [comment]
Good morning @Hobokens 

you're so right.

We need jquery-ui just for the datepicker and I want to replace that with another solution like bootstrap-calendar or maybe you have another cool slim idea?

But yes, as first step a reduction of jquery-ui would be possible.

Stefan

**Comment by maslme** [comment]
I would also prefer a possibility to deactivate jQuery and jQueryUi Loading via your Extension - I had some dificults when more Extensions loading each on their own jQuery.

**Comment by froemken** [comment]
@maslme 
events2 comes with 2 TypoScript constants:

```
plugin.tx_events2.settings.includeJQueryLibrary
plugin.tx_events2.settings.includeJQueryUiLibrary
```

You can set both to `0` and you're done.

Stefan

**Comment by froemken** [comment]
Hello @Hobokens 

I just have replaced jquery and jquery-ui with LitePicker in branch typo3_11_compatibility. Now it's super fast ;-)

Stefan
