### ISSUE TITLE
Possibility to extend AJAX-Response FindDaysForMonth

### ISSUE THREAD

**Issue by TheJotob** [jweiland-net/events2#286]
It would be nice if developers got the chance to change or extend the output of the AJAX-Response from the class JWeiland\Events2\Ajax\FindDaysForMonth by using an EventListener.
I.e. to get the names of all categories that an event belongs to.

**Comment by froemken** [comment]
Hi @TheJotob 

I just have added an EventDispatcher to this AjaxCall. Could you please test it on current dev-master of events2?

Nice greetings

Stefan

**Comment by TheJotob** [comment]
Hi @froemken ,

wow that was super quick. Thank you so much! Just a quick question: Is the event not missing a set function? Or some function to modify the days array?

Nice greetings,
Joachim

**Comment by froemken** [comment]
AHHHHH, yes, it's an array not an object. I'm so sorry.

**Comment by froemken** [comment]
@TheJotob I have added a setDays to the event.

**Comment by TheJotob** [comment]
@froemken perfect. Thank you so much. We will test it out tomorrow :)

**Comment by TheJotob** [comment]
We tested it and it works like a charm :)
Thank you so much @froemken
