### ISSUE TITLE
Setting UID of root category not working?

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#294]
Hi,

I would like to restrict the selection of categories for events in backend event editing. For this I have created a parent category with the UID 13 and entered 13 in the TS constants for "UID if root category". Unfortunately, the restriction of the selection in the backend does not work. I still see all other sys categories. The event categories are created in the sysfolder with the event records. All other sys categories are created in a central sysfolder. The "Default storage PID" is set to the sysfolder with the event data records.

Should this work as described above, or am I making a mistake in my thinking or have I missed something?

**Comment by froemken** [comment]
Hallo @derBoogie 

with TS constants it will never be possible to update fields in backend. These constants are for frontend search and frontend event creation.
As you need a solution for backend please have a look into extension settings of events2. There you will find an option called "rootUid". Please set that to your parent category, clear cache and reload backend.

**Comment by froemken** [comment]
https://docs.typo3.org/p/jweiland/events2/master/en-us/Configuration/Extension/Index.html#rootuid

**Comment by derBoogie** [comment]
Hi @froemken,
thanks for your fast reply and the hint to rootUId in extension settings.
I entered the rootUid "13" in the extension settings, cleared the TYPO3 and PHP cache and reloaded the TYPO3 backend. Unfortunately, I still see all categories, see screenshot:
![grafik](https://user-images.githubusercontent.com/1611217/125266398-1665a080-e306-11eb-9069-aee99f3912ef.png)

**Comment by froemken** [comment]
Hi @derBoogie 

please use official TYPO3 API to reduce the category tree in event records:
https://docs.typo3.org/m/typo3/reference-tsconfig/10.4/en-us/PageTsconfig/TceForm.html#config-treeconfig

Not tested, but it should look like that:
`TCEFORM.tx_events2_domain_model_event.categories.config.treeConfig.rootUid`

Stefan

**Comment by derBoogie** [comment]
Thank you @froemken, this works =)
