### ISSUE TITLE
Error while indexing with ke_search

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#295]
Hi,
TYPO3 10.4.17, events2 7.0.4.

While indexing my website with ke_search I get the following error and the indexing process stops. 

`
Too few arguments to function JWeiland\Events2\Service\DatabaseService::__construct(), 0 passed in /var/www/vhosts/9XXXX7.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3474 and exactly 2 expected`

Regards
Hobokens

**Comment by froemken** [comment]
Hi @Hobokens 

can you please activate Dev-Mode and send me the back-trace?
It seems that DatabaseService was called by GeneralUtility, but it's the job of DependencyInjection.
Currently I don't find any line of code in events2 where DatabaseService was called directly, that's why I need the back-trace.

Thank you for your help.

Stefan

PS: I'm on holiday for the next 2 weeks. So my next answer may need some days ;-)

**Comment by Hobokens** [comment]
Hi @froemken ,

I hope that this is helpful for you and and have nice holidays!

`1/1) ArgumentCountError

Too few arguments to function JWeiland\Events2\Service\DatabaseService::__construct(), 0 passed in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3474 and exactly 2 expected
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/events2/Classes/Service/DatabaseService.php line 40

     * @var DateTimeUtility
     */
    protected $dateTimeUtility;

    public function __construct(ExtConf $extConf, DateTimeUtility $dateTimeUtility)
    {
        $this->extConf = $extConf;
        $this->dateTimeUtility = $dateTimeUtility;
    }

at JWeiland\Events2\Service\DatabaseService->__construct()
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3474

            return self::$container->get($className);
        }

        // Create new instance and call constructor with parameters
        $instance = new $finalClassName(...$constructorArguments);
        // Register new singleton instance, but only if it is not a known PSR-11 container service
        if ($instance instanceof SingletonInterface && !(self::$container !== null && self::$container->has($className))) {
            self::$singletonInstances[$finalClassName] = $instance;
        }

at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('JWeiland\\Events2\\Service\\DatabaseService')
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/sitepackage_hfm_wuerzburg/Classes/Indexer/Events2.php line 84

            ->add(GeneralUtility::makeInstance(DeletedRestriction::class));

        $orConstraints = [];

        $events2DbService = GeneralUtility::makeInstance(\JWeiland\Events2\Service\DatabaseService::class);

        $orConstraints[] = $events2DbService->getConstraintForSingleEvents($queryBuilder);
        $orConstraints[] = $events2DbService->getConstraintForDurationEvents($queryBuilder);
        $orConstraints[] = $events2DbService->getConstraintForRecurringEvents($queryBuilder);

at HochschuleFuerMusikWuerzburg\SitepackageHfmWuerzburg\Indexer\Events2->customIndexer(array('uid' => 1, 'pid' => 945, 'tstamp' => 1560776538, 'crdate' => 1549032858, 'cruser_id' => 3, 'deleted' => 0, 'hidden' => 0, 'title' => 'Seitensuche', 'storagepid' => '945', 'targetpid' => null, 'startingpoints_recursive' => '1', 'single_pages' => '', 'sysfolder' => null, 'index_content_with_restrictions' => 'no', 'type' => 'page', 'index_news_category_mode' => 1, 'index_news_category_selection' => null, 'index_extnews_category_selection' => null, 'index_news_archived' => 0, 'index_news_useHRDatesSingle' => 0, 'index_news_useHRDatesSingleWithoutDay' => 0, 'index_use_page_tags' => 0, 'index_use_page_tags_for_files' => 0, 'index_page_doctypes' => '1,2,5', 'directories' => null, 'fileext' => 'pdf,ppt,doc,xls,docx,xlsx,pptx', 'filteroption' => 0, 'fal_storage' => -1, 'contenttypes' => 'text,textmedia,textpic,bullets,table,html,header,uploads', 'index_news_files_mode' => 0), object(TeaminmediasPluswerk\KeSearch\Indexer\IndexerRunner))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/ke_search/Classes/Indexer/IndexerRunner.php line 212

                        'Custom indexer "' . $this->indexerConfig['title'] . '" started',
                        $this->indexerConfig
                    );
                    if ($indexingMode == IndexerBase::INDEXING_MODE_FULL || !method_exists($searchObj, 'startIncrementalIndexing')) {
                        $message = $searchObj->customIndexer($indexerConfig, $this);
                    } else {
                        $message = $searchObj->startIncrementalIndexing($indexerConfig, $this);
                    }
                    if ($message) {

at TeaminmediasPluswerk\KeSearch\Indexer\IndexerRunner->startIndexing(true, array('allowEmptySearch' => '1', 'enableExplicitAnd' => '1', 'enablePartSearch' => '1', 'finishNotification' => '0', 'loglevel' => 'ERROR', 'multiplyValueToTitle' => '2', 'notificationRecipient' => '', 'notificationSender' => 'no_reply@domain.com', 'notificationSubject' => '[KE_SEARCH INDEXER NOTIFICATION]', 'pathCatdoc' => '/usr/bin/', 'pathPdfinfo' => '/usr/bin/', 'pathPdftotext' => '/usr/bin/', 'searchWordLength' => '3'), '', 0)
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/ke_search/Classes/Controller/BackendModuleController.php line 140


        // action: start indexer or remove lock
        if ($this->do == 'startindexer') {
            // start indexing in verbose mode with cleanup process
            $content .= $indexer->startIndexing(true, $this->extConf, '', $this->indexingMode);
        } else {
            if ($this->do == 'rmLock') {
                // remove lock from registry - admin only!
                if ($this->getBackendUser()->isAdmin()) {

at TeaminmediasPluswerk\KeSearch\Controller\BackendModuleController->startIndexingAction()
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php line 498

        }
        $validationResult = $this->arguments->validate();
        if (!$validationResult->hasErrors()) {
            $this->eventDispatcher->dispatch(new BeforeActionCallEvent(static::class, $this->actionMethodName, $preparedArguments));
            $actionResult = $this->{$this->actionMethodName}(...$preparedArguments);
        } else {
            $actionResult = $this->{$this->errorMethodName}();
        }

at TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod()
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php line 426

        $this->view = $this->resolveView();
        if ($this->view !== null) {
            $this->initializeView($this->view);
        }
        $this->callActionMethod();
        $this->renderAssetsForRequest($request);
    }

    /**

at TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest(object(TYPO3\CMS\Extbase\Mvc\Web\Request), object(TYPO3\CMS\Extbase\Mvc\Web\Response))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/ke_search/Classes/Controller/AbstractBackendModuleController.php line 113

    public function processRequest(
        RequestInterface $request,
        ResponseInterface $response
    ) {
        parent::processRequest($request, $response);

        // We are here ony if the action did not throw exceptions (==successful and not forwarded). Save the action.
        $this->storeLastModuleInformation();
    }

at TeaminmediasPluswerk\KeSearch\Controller\AbstractBackendModuleController->processRequest(object(TYPO3\CMS\Extbase\Mvc\Web\Request), object(TYPO3\CMS\Extbase\Mvc\Web\Response))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php line 89

                throw new InfiniteLoopException('Could not ultimately dispatch the request after ' . $dispatchLoopCount . ' iterations. Most probably, a @' . IgnoreValidation::class . ' annotation is missing on re-displaying a form with validation errors.', 1217839467);
            }
            $controller = $this->resolveController($request);
            try {
                $controller->processRequest($request, $response);
            } catch (StopActionException $ignoredException) {
            }
        }

at TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch(object(TYPO3\CMS\Extbase\Mvc\Web\Request), object(TYPO3\CMS\Extbase\Mvc\Web\Response))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/extbase/Classes/Mvc/Web/BackendRequestHandler.php line 36

    {
        $request = $this->requestBuilder->build();
        /** @var \TYPO3\CMS\Extbase\Mvc\ResponseInterface $response */
        $response = $this->objectManager->get(Response::class);
        $this->dispatcher->dispatch($request, $response);
        return $response;
    }

    /**

at TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest()
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/extbase/Classes/Core/Bootstrap.php line 226

        $this->initialize($configuration);

        $requestHandler = $this->requestHandlerResolver->resolveRequestHandler();
        /** @var ExtbaseResponse $extbaseResponse */
        $extbaseResponse = $requestHandler->handleRequest();

        // Convert to PSR-7 response and hand it back to TYPO3 Core
        $response = $this->convertExtbaseResponseToPsr7Response($extbaseResponse);
        $this->resetSingletons();

at TYPO3\CMS\Extbase\Core\Bootstrap->handleBackendRequest(object(TYPO3\CMS\Core\Http\ServerRequest))
at call_user_func_array(array(object(TYPO3\CMS\Extbase\Core\Bootstrap), 'handleBackendRequest'), array(object(TYPO3\CMS\Core\Http\ServerRequest)))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Http/RouteDispatcher.php line 66

        }
        $targetIdentifier = $route->getOption('target');
        $target = $this->getCallableFromTarget($targetIdentifier);
        $arguments = [$request];
        return call_user_func_array($target, $arguments);
    }

    /**
     * Wrapper method for static form protection utility

at TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Http/RequestHandler.php line 94

        // there are Core classes that need the Request object but do not get it handed in
        $this->resetGlobalsToCurrentRequest($request);
        try {
            // Check if the router has the available route and dispatch.
            return $this->dispatcher->dispatch($request);
        } catch (InvalidRequestTokenException $e) {
            // When token was invalid redirect to login
            $loginPage = GeneralUtility::makeInstance(UriBuilder::class)->buildUriFromRoute('login');
            return new RedirectResponse((string)$loginPage);

at TYPO3\CMS\Backend\Http\RequestHandler->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/extbase/Classes/Middleware/SignalSlotDeprecator.php line 49

     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $this->dispatcher->reportDeprecatedSignalSlots();
        return $handler->handle($request);
    }
}

at TYPO3\CMS\Extbase\Middleware\SignalSlotDeprecator->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(TYPO3\CMS\Backend\Http\RequestHandler))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Middleware/SiteResolver.php line 69

            }
            $site = $this->siteMatcher->matchByPageId($pageId, $rootLine);
            $request = $request->withAttribute('site', $site);
        }
        return $handler->handle($request);
    }
}

at TYPO3\CMS\Backend\Middleware\SiteResolver->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Middleware/AdditionalResponseHeaders.php line 41

     * @return ResponseInterface
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $response = $handler->handle($request);
        foreach ($GLOBALS['TYPO3_CONF_VARS']['BE']['HTTP']['Response']['Headers'] ?? [] as $header) {
            [$headerName, $value] = explode(':', $header, 2);
            $response = $response->withAddedHeader($headerName, trim($value));
        }

at TYPO3\CMS\Backend\Middleware\AdditionalResponseHeaders->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Middleware/OutputCompression.php line 47

        ob_clean();
        // Initialize output compression if configured
        $this->initializeOutputCompression();

        return $handler->handle($request);
    }

    /**
     * Initialize output compression if configured

at TYPO3\CMS\Backend\Middleware\OutputCompression->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php line 79

        $GLOBALS['LANG'] = LanguageService::createFromUserPreferences($GLOBALS['BE_USER']);
        // Re-setting the user and take the workspace from the user object now
        $this->setBackendUserAspect($GLOBALS['BE_USER']);

        $response = $handler->handle($request);

        // If no backend user is logged-in, the cookie should be removed
        if (!GeneralUtility::makeInstance(Context::class)->getAspect('backend.user')->isLoggedIn()) {
            $GLOBALS['BE_USER']->removeCookie($GLOBALS['BE_USER']->name);

at TYPO3\CMS\Backend\Middleware\BackendUserAuthenticator->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php line 58


        // Add the route path to the request
        $request = $request->withAttribute('routePath', $pathToRoute);

        return $handler->handle($request);
    }
}

at TYPO3\CMS\Backend\Middleware\BackendRouteInitialization->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php line 55

            [$server, $address] = explode('/', $url, 2);
            return new RedirectResponse('https://' . $server . $sslPortSuffix . '/' . $address);
        }

        return $handler->handle($request);
    }
}

at TYPO3\CMS\Backend\Middleware\ForcedHttpsBackendRedirector->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php line 75

            $request->getAttribute('normalizedParams')->getRemoteAddress(),
            trim((string)$GLOBALS['TYPO3_CONF_VARS']['BE']['IPmaskList'])
        );

        return $handler->handle($request);
    }

    /**
     * Check adminOnly configuration variable and redirects to an URL in file typo3conf/LOCK_BACKEND

at TYPO3\CMS\Backend\Middleware\LockedBackendGuard->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php line 45

     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $request = $request->withAttribute('normalizedParams', NormalizedParams::createFromRequest($request));
        return $handler->handle($request);
    }
}

at TYPO3\CMS\Core\Middleware\NormalizedParamsAttribute->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172


                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php:138$111->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 78

     * @return ResponseInterface
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->tip->handle($request);
    }

    /**
     * Seed the middleware stack with the inner request handler

at TYPO3\CMS\Core\Http\MiddlewareDispatcher->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/AbstractApplication.php line 85

     * @return ResponseInterface
     */
    protected function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->requestHandler->handle($request);
    }

    /**
     * Set up the application and shut it down afterwards

at TYPO3\CMS\Core\Http\AbstractApplication->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/backend/Classes/Http/Application.php line 72

        $request = $request->withAttribute('applicationType', $applicationType);

        // Set up the initial context
        $this->initializeContext();
        return parent::handle($request);
    }

    /**
     * Check if LocalConfiguration.php and PackageStates.php exist

at TYPO3\CMS\Backend\Http\Application->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/AbstractApplication.php line 97

    final public function run(callable $execute = null)
    {
        try {
            $response = $this->handle(
                ServerRequestFactory::fromGlobals()
            );
            if ($execute !== null) {
                call_user_func($execute);
            }

at TYPO3\CMS\Core\Http\AbstractApplication->run()
in /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/index.php line 25

// Set up the application for the backend
call_user_func(function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_BE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Backend\Http\Application::class)->run();
});

at {closure}()
in /var/www/vhosts/9XXXX7.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/index.php line 26

call_user_func(function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_BE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Backend\Http\Application::class)->run();
});


`

**Comment by Hobokens** [comment]
Hi @froemken 
I'm not sure anymore, that events2 stops the indexing process of ke_search. Right now I always get a '504 Gateway Time-out'. (I reported this issue to the JWeiland Support.)
Regardless of this, I still find the error message described above in the log files.

**Comment by Hobokens** [comment]
Hi @froemken,
ke_search is still not working. Whenever the indexing process starts I get the error message 


`  | Core: Exception handler (CLI):  Uncaught TYPO3 Exception: Too few arguments to function  JWeiland\Events2\Service\DatabaseService::__construct(), 0 passed in  /var/www/vhosts/XxXx.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php  on line 3474 and exactly 2 expected \| ArgumentCountError thrown in file   /var/www/vhosts/XxXx.jweiland-hosting.de/httpdocs/typo3cms/XxXx/typo3conf/ext/events2/Classes/Service/DatabaseService.php  in line 40`

**Comment by froemken** [comment]
Hello @Hobokens 

I see that a foreign TYPO3 extension calls DatabaseService of events2. So I have just set all PHP classes in Service folder as public for TYPO3s Dependency Injection.

I have just uploaded version 7.0.8 to TER and composer

Have a nice start into this new week.

Stefan

**Comment by Hobokens** [comment]
Hello @froemken,
thanks for the update. Unfortunately, the problem remains after upgrading to version 7.0.8 and clearing the folder mentioned above.

`Mon, 02 Aug 2021 12:00:30 +0200 [CRITICAL] request="5874840c656f3" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (CLI): Uncaught TYPO3 Exception: Too few arguments to function JWeiland\Events2\Service\DatabaseService::__construct(), 0 passed in /var/www/vhosts/9xxxx7.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3474 and exactly 2 expected | ArgumentCountError thrown in file /var/www/vhosts/9xxxx7.jweiland-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/events2/Classes/Service/DatabaseService.php in line 40 - {"TYPO3_MODE":"BE","exception":{}}`

Downgrading to version 6.3.x and clearing the folder `/typo3temp/var/cache/` solves the problem and `ke_search` runs without problems.

Have a wonderful day!
Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

I have just uploaded version 7.0.9 which sets the PHP classes in Services directory as public. Sorry, there was a mistake within one of my last patches.
Locally I can now access DatabaseService from foreign extensions without any problems.

Please try the new version and give me feedback.

Have a nice start into the coming weekend

Stefan

**Comment by Hobokens** [comment]
Hello @froemken ,
perfect, the problem is solved. Thanks a lot!
Have a nice weekend
hobokens
