### ISSUE TITLE
Sorting of categories in search form

### ISSUE THREAD

**Issue by netthinks** [jweiland-net/events2#299]
Categories in search form are sorted by uid, not by sorting field or alphabetically. Sorting cannot be configured viy typoscript or flexform.

**Comment by froemken** [comment]
Hello @netthinks 

thank you for that hint. You're right, they are not sorted. I'm wondering that non of our customers mentioned that :-)

I will build a patch in future, but that will need some time. So there are currently two possibilities for you, if you need that now:

1.) Install EXT:vhs and use the sortable ViewHelper
2.) If you are a programmer, you can use this Event: https://github.com/jweiland-net/events2/blob/master/Classes/Controller/SearchController.php#L87-L102 to modify the ordering of the categories.

Nice greetings

Stefan

**Comment by froemken** [comment]
Hello @netthinks 

I have just released version 7.0.10 which sorts categories in search form

Stefan
