### ISSUE TITLE
Database error while updating TYPO3 Core

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#303]
Hi,
when I update TYPO3 core (from 10.4.17 to 10.4.20) I get the following error:

[ Doctrine\DBAL\Exception\InvalidFieldNameException ] An exception occurred while executing 'SELECT COUNT(*) FROM 
tx_events2_domain_model_event e INNER JOIN tx_events2_event_organizer_mm eo_mm ON e .organizer =  eo_mm.uid_local WHERE (e.organizer > ?) AND (e.deleted = 0) with params [0]: Unknown column 'e.organizer' in 'where clause

The error is understandable because the column is called "organizers".
What I do not understand where this query is made?

Currently Events2 is installed in version 7.0.4.
Could an update to version 7.0.10 help?

**Comment by froemken** [comment]
@derBoogie 

thank you for this report. I think an update will not help. The only place I found, which relates to this query is here:
https://github.com/jweiland-net/events2/blob/7.0.4/Classes/Updater/MigrateOrganizerToMMUpdater.php#L58-L61

This is an Updater to update the old organizer column to organizers with MM table.

So it seems that you already have deleted the old organizer column before executing the updater. IMO you can't mark an updater as done, so please create this old organizer column again INT DEFAULT 0 and execute the updater. Afterwards the updater should be marked as done and the error should be gone.

Please keep me informed if that works. If not I will add a check, if organizer column exists before executing the updater.

Stefan

**Comment by derBoogie** [comment]
Hi @froemken 

thanks for your fast reply.
Which updater do you mean?
Where can I find it?

Greetings TJ

**Comment by froemken** [comment]
@derBoogie 

I have posted a link to the UpgradeWizard. It's name is "MigrateOrganizerToMMUpdater" with title "[events2] Migrate organizer".
Please login as Administrator to your TYPO3 backend. Open module "Upgrade" on the left, if needed please enter the Installtool- or the password of the current user, click on "Run Upgrade Wizards" at second panel called "Upgrade Wizard". Here you should find and "Execute" the Upgrade Wizard of events2.

Stefan

**Comment by derBoogie** [comment]
Hi @froemken 

your solution worked!

I hat to create the column detail_informations in table ..._events as well.

Greetings TJ
