### ISSUE TITLE
Support for TYPO3 11

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#305]
Hi, 
are there any news for TYPO3 11 support. Will it be supported? 
Thanks.

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

good news. Just yesterday I got some tickets from my projectmanager to upgrade various extensions. I have started with infinitescrolling. Next: maps2 and at third position I will upgrade events2. But I can't tell you a finishing date.

Stefan

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

maps2 is released, so now I have time to upgrade events2. Keep an eye on the new commits of branch typo3_11_compatibility.

Stefan

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

I have just released version 8.0.0 to TER and composer. Yeah. Happy birthday :-)

Please read Upgrade Notes carefully: https://docs.typo3.org/p/jweiland/events2/main/en-us/AdministratorManual/Upgrade/Index.html

Stefan
