### ISSUE TITLE
Routing of events with uid instead of date and time 

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#309]
Hi,

is it possible to configure the route of events with uid instead of date and time?
The problem is that the date or time of an event can change in advance and then the already communicated liks of the events are no longer valid.

My current config looks like this:
```
routes:
...
  routePath: '/{event}'
...
requirements:
...
  event: '^[a-zA-Z0-9\-\/]+$'
...
aspects:
...
  event:
    type: PersistedPatternMapper
      tableName: tx_events2_domain_model_event
      routeFieldName: uid,path_segment
      routeFieldPattern: '^(?P<uid>\d+)/(?P<path_segment>.+)$'
      routeFieldResult: '{uid}/{path_segment}'
...
```

The event url looks like this:
.../event/3/event-title/?tx_events2_events%5Btimestamp%5D=1632405600&cHash=6c4ea99bdb3f0411b990b73bb00e242b

How can I remove or bybass the params "tx_events2_events[timestamp]" and cHash?

Greetings
TJ

**Comment by derBoogie** [comment]
I have found a working solution.
To remove the timestamp parameter from the talking URL, I wrote a simple routing ascpect ParamBypassAspect.php:
`<?php
declare(strict_types=1);
namespace Vendor\Extension\Routing\Aspect;
use TYPO3\CMS\Core\Routing\Aspect\StaticMappableAspectInterface;
class ParamBypassAspect implements StaticMappableAspectInterface
{
  public function generate(string $value): ?string
  {		
    return '';
  }
  public function resolve(string $value): ?string
  {
    return '';
  }
}`

The config.yaml looks like this:
`routes:
...
  -
    routePath: '/{event_title}{date}'
    _controller: 'Day::show'
    _arguments:
      date: timestamp
      event_title: event
...
requirements:
  date: '.*'
  event_title: '^[a-zA-Z0-9\-]+$'
...
aspects:
  date:
    type: ParamBypassAspect
...`

**Comment by froemken** [comment]
Hello @derBoogie 

I have though often to do so, but you miss one thing:
If you save an event in BE the DayGenerator analyzes the event, deletes all related day records and creates new ones. So, with each save, all of your previous day UIDs are gone and your links are invalid. Further, events2 works in a timeframe (-3 months -> + 6 months). To update the day records you should activate the events2 re-generate days scheduler tasks. It also deletes all related day records and creates them again. So, in a correct configured system, all links to an events2 record will get invalid with your solution.

Only if you work with single events you can set timestamp in URL to 0 or work with your ByPass solution. In that special case events2 have various fallbacks. First, it will search for the next upcoming event, if not found, it will try to find the last previous event (somewhere within the last -3 months) and if date is out of timeframe (< -3 month, > +6 month) it will display the date of column event_begin which will be OK for you, if you have single events only. But in case of a recurring events this may result in a date which can be 5 years old. So, be careful what you're doing.

Nice greetings

Stefan

**Comment by derBoogie** [comment]
Hi @froemken

thank you very much for the detailed explanation.

I already thought that it will not work properly without the timestamp parameter.

Greetings
TJ
