### ISSUE TITLE
getDayTime() Errror

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#318]
Hi,
I'm using TYPO3 10.4.21 and events 7.0.12.

I sometimes get these errors for past events:

`Core:  Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to  JWeiland\Events2\Service\DayRelationService::getDayTime() must be an  instance of DateTime, null given, called in  /var/www/vhosts/xxxxx.jweiland-hosting.de/httpdocs/typo3cms/xxxxx/typo3conf/ext/events2/Classes/Service/DayRelationService.php  on line 247 \| TypeError thrown in file  /var/www/vhosts/xxxxx.jweiland-hosting.de/httpdocs/typo3cms/xxxxx/typo3conf/ext/events2/Classes/Service/DayRelationService.php  in line 216. Requested URL:  https://www.my-domain.de/veranstaltungen/kalender/event/2020-11-20_0000/name-of-event |  `

Regards
Hobokens

**Comment by froemken** [comment]
Just an information for me:

This is the line where the problem happens:
https://github.com/jweiland-net/events2/blob/7.0.12/Classes/Service/DayRelationService.php#L247

But in these lines I set $this->firstDateTime explicit: https://github.com/jweiland-net/events2/blob/7.0.12/Classes/Service/DayRelationService.php#L127-L129 So currently don't know how this can be null.

Check first: Will $this->firstDateTime be modified somewhere?
Second: Quote: "get these errors for past events" Check, if this will happen in range of `recurringPast` (-3 months by default) only or for events out of this range (-5 month f.e.)

**Comment by Hobokens** [comment]
Hi @froemken,
thanks for your questions.
1) There is no modification. I'm using the extension 'reserve'. But this shouldn't be important for this error.
2) It seems to happen only for events out of range.

Regards
Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

thank you for these information. I have found the issue and solved it with version 7.1.3 and 8.0.0.

Stefan
