### ISSUE TITLE
[FEATURE REQUEST] choose include or exclude of categories in list view

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#320]
It would be great if there was a possibility to choose between include or exclude (whiltelisting/blacklisting) of categories in the list view.
E.g. show all categories except this one.

Regards
TJ

**Comment by froemken** [comment]
Hello @derBoogie 

hmm. I can't do that in Repository, as this will also reduce the related events. I can add such a method in Domainmodel, but you can't call it with arguments from the View (Fluid). So IMO there is only a solution in View directly. 

So maybe there is a ViewHelper in TYPO3 Extension `vhs` to reduce arrays or ObjectStorages or you have to reduce the set of categories on your own. Just an example (not-tested):

```
<ul>
<f:for each="{event.categories}" as="category">
    <f:if condition="{category.uid} == 3">
        <li>{category.title}</li>
    </f:if>
</f:for>
</ul>

```

Nice greetings

Stefan

**Comment by derBoogie** [comment]
Hi @froemken

thank's for your explanation.

I have made it similar to your suggestion.
In may case there is only one category to be excluded:

```
<ul>
<f:for each="{event.categories}" as="category">
    <f:if condition="{category.uid} != {settings.excludeCategoryUid}">
        <li>{category.title}</li>
    </f:if>
</f:for>
</ul>
```

Greetings
TJ
