### ISSUE TITLE
Listenausgabe kein Datum bei März Terminen

### ISSUE THREAD

**Issue by christianbacher** [jweiland-net/events2#321]
Guten Tag,

Ich bräuchte bitte Ihre Hilfe.

Wir verwenden Typo3 9 und events2 | 6.3.3

Die Termine im Februar werden so ausgeben
Sa 26. Feb 2022 | Beginn: 19:30

und im März fehlt das Datum komplett.
| Beginn: 19:30
Dave & the Coverdudes - Coverband

haben Sie eine Idee.
Danke
lg. Christian Bacher

**Comment by froemken** [comment]
Hallo @christianbacher 

bitte prüf mal die locale-Einstellung in der SitesConfiguration. Die muss exakt mit der locale übereinstimmen, wie sie auch im Betriebssystem hinterlegt ist `locale -a`. Bitte nicht einfach nur `en` eintragen, sondern exakt so, wie es auf der Shell ausgegeben wird. Also z.B.: en_US.UTF-8`. Dabei bitte auch Groß- und Kleinschreibung beachten.

Evtl. im Installtool auch mal die Timezone prüfen und auf: Europe/Berlin umstellen.

Schönen Gruß

Stefan

**Comment by christianbacher** [comment]
Hallo Stefan,

funktioniert :-) - danke für den schnellen Support.

liebe Grüße 
Christian
