### ISSUE TITLE
[TYPO3 11] create new location - No dropdown for country available

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#323]
When trying to create a new location, there is no value available inside the country dropdown

<img width="198" alt="Bildschirmfoto 2022-02-11 um 15 04 36" src="https://user-images.githubusercontent.com/57705869/153605461-6d4dd07a-5109-44b7-90cb-2def3a6a06f3.png">

When I try to save it, I get the error: 
`'Incorrect integer value: '' for column db.tx_events2_domain_model_location.country at row 1'`

TYPO3 11.5.6
events2: dev-typo3_11_compatibility
maps2: dev-typo3_11_compatibility
static_info_tables: dev-master

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

this was a problem with static_info_tables. Please install most current version of static_info_tables and execute UpdateWizard of static_info_tables in ExtensionManager to create the needed records.

Stefan
