### ISSUE TITLE
[TYPO3 11] Too few arguments AddressHelper __construct

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#324]
When trying to save a location which is already created before I get the error: 
```
(1/1) ArgumentCountError
Too few arguments to function JWeiland\Maps2\Helper\AddressHelper::__construct(), 0 passed in /var/www/html/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3199 and exactly 1 expected
```

**Comment by PhilippKuhlmay** [comment]
Adding 
```
JWeiland\Maps2\Helper\AddressHelper:
  public: true
``` 
to Services.yaml solved this issue for me.

**Comment by froemken** [comment]
Hello @PhilippKuhlmay,

this is not a problem of events2. As you have connected events2 with maps2 over Maps2Registry the call to store location records will be transferred to a maps2 hook.

I have solved this issue just yesterday: https://github.com/jweiland-net/maps2/commit/b6858fc65b6d71066034db646792caa25b9e27f1

Thank you for making events2/maps2 better extensions

Stefan
