### ISSUE TITLE
[TYPO3 11] Argument must be type of extConf, null given

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#325]
After saving a location, I get the following error:
```
(1/1) TypeError
JWeiland\Maps2\Client\Request\GoogleMaps\GeocodeRequest::__construct(): Argument #1 ($extConf) must be of type JWeiland\Maps2\Configuration\ExtConf, null given
```

**Comment by froemken** [comment]
Good morning @PhilippKuhlmay 

thank you for testing our extensions. I can confirm this issue and have solved it just yesterday: https://github.com/jweiland-net/maps2/commit/b6858fc65b6d71066034db646792caa25b9e27f1

It's a problem of "maps" ;-)

Stefan
