### ISSUE TITLE
[TYPO3 11] Typed property must not be accessed before initialization 

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#329]
I now get the error: `Typed property JWeiland\Events2\Domain\Model\Event::$tstamp must not be accessed before initialization` and several other with _crdate_ etc.

After adding `= null` to the variables `$crdate, $tstamp, $starttime, $endtime` inside `EXT:events2/Classes/Domain/Traits/Typo3PropertiesTrait.php` it works again.

_I only get this error sometimes, not always._

**Comment by PhilippKuhlmay** [comment]
And also inside EXT:events2/Classes/Domain/Model/Time.php
* timeBeginAsDateTime
* timeEntryAsDateTime
* timeEndAsDateTime

Maybe there are some other lines which needs to be changed but this is all I found untill now.

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for your help. I have added default values to these properties to prevent this issue.

New version is available in typo3_11_compatibility branch:
https://github.com/jweiland-net/events2/blob/typo3_11_compatibility/Classes/Domain/Model/Time.php#L53-L57

Nice greetings

Stefan
