### ISSUE TITLE
Translation for settings.pidOfListPage is not correct

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#332]
The german translation for `settings.pidOfListPage` is a little bit confusing.
It says: **PID der Seite, auf der die GoogleMaps Karte angezeigt werden soll** 
As it is possible to also include OpenStreetMap i suggest to change it into **PID der Seite, auf der die Karte angezeigt werden soll**

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

as maps2 is not a hard dependency to events2 and location page must not display a map I have updated both translations.
The new german value is: `PID der Seite für den Veranstaltungsort`

I have pushed the new values for branch typo3_11_compatibility already.

If you need that for TYPO3 10 please update that value at crowdin or with help of TypoScript

Thank you for your help.

Stefan
