### ISSUE TITLE
CSS issue with event which is "top of list"

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#336]
Hi, 

I set an event as "top of list" and there is a small CSS issue. The li-tag has the class `list-group-itemlist-group-item-info` which should be `list-group-item list-group-item-info`

<img width="449" alt="Bildschirmfoto 2022-03-16 um 17 21 27" src="https://user-images.githubusercontent.com/57705869/158637855-c9b3baaa-0798-4607-9d9f-594063700d96.png">

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

I have merged your PR. Further I have added that change to typo3_11_compatibility branch.

Thank you for your help

Stefan
