### ISSUE TITLE
[TYPO3 11] Try to access array offset in TimeFactory.php line 179

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#338]
I currently get the following error at the detail page for an event.
`PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3conf/ext/events2/Classes/Domain/Factory/TimeFactory.php line 179`

<img width="1172" alt="Bildschirmfoto 2022-03-24 um 09 19 46" src="https://user-images.githubusercontent.com/57705869/159873090-45bf96c9-37af-42a2-97e6-f0ee7ba105a4.png">

TYPO3 11.5.8
events2: typo3_11_compatibility

The URL is https://blablabla/details?tx_events2_show%5Baction%5D=show&tx_events2_show%5Bcontroller%5D=Day&tx_events2_show%5Bevent%5D=5&tx_events2_show%5Btimestamp%5D=1649098800

Switching the get parameter from `tx_events2_list` to `tx_events2_show` in https://github.com/jweiland-net/events2/blob/typo3_11_compatibility/Classes/Domain/Factory/TimeFactory.php#L178 worked in my case.

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for your help. I have found the line with your help and just pushed a new version to typo3_11_compatibility branch.

Stefan
