### ISSUE TITLE
[TYPO3 11] Translation for plugin type "list week" is missing

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#339]
Hi, the translation for the title of the plugin type **list week** (`listType.listWeek`) is missing. 
Instead there is a translation for `listType.listThisWeek` inside the FlexForms.xlf but this isn't used.

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for your help. I have just updated the translation key in FlexForm and pushed my changes to typo3_11_compatibility branch

Stefan
