### ISSUE TITLE
[TYPO3 11] Link to an event inside the calendar shows exception

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#340]
Hi,

I have the plugin events2_calendar which shows the calendar. The days with events are yellow but when I try to open this day, I get an exception.

<img width="279" alt="Bildschirmfoto 2022-03-24 um 11 22 13" src="https://user-images.githubusercontent.com/57705869/159895698-e4d0642b-4082-491e-b61d-a4fa7a6076b9.png">

<img width="1142" alt="Bildschirmfoto 2022-03-24 um 11 21 57" src="https://user-images.githubusercontent.com/57705869/159895656-fffaa5cc-402f-4f0e-b11c-c01756475958.png">

The URL is
https://blablabla.de/termine?tx_events2_events%5Baction%5D=showByTimestamp&tx_events2_events%5Bcontroller%5D=Day&tx_events2_events%5Btimestamp%5D=1646607600&cHash=somehash

TYPO3: 11.5.8
Events2: typo3_11_compatibility

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for your help. The PageTitleProvider should never be called while listing all events of a given date.
I have found the mistake and pushed a new version to typo3_11_compatibility branch.

Stefan

**Comment by PhilippKuhlmay** [comment]
The exception is gone.

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

I have just uploaded a new version to typo3_11_compatibility which shows all records of a chosen day.

Thank you for your help

Stefan
