### ISSUE TITLE
[TYPO3 11] Events shows wrong date and time depending on the winter/summer time

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#342]
Hi I have an recurring event which goes from Oktober till November. After the time in Germany changes to winter time, the event shows a wrong date and time.

Given:
Recurring event which starts at 01.10.2022 and ends at 30.11.2022
event_time - time_begin: 18:00
recurring each 4 weeks
no exceptions or other configuration

In frontend I get the following dates:
Saturday 01. October 2022 Begin 18:00
Saturday 29. October 2022 Begin 18:00
Friday 25. November 2022 Begin 17:00 (should be Saturday 18:00)

_The timechange to winter time is at 30. October 2022._

<img width="831" alt="Bildschirmfoto 2022-03-24 um 14 08 47" src="https://user-images.githubusercontent.com/57705869/159922993-5e214175-2730-4e98-a533-3d898ff34983.png">

Database:
```
uid	pid	day	day_time	sort_day_time	same_day_time
396	126	1664575200	1664640000	1664640000	1664640000
397	126	1666994400	1667059200	1667059200	1667059200
398	126	1669413600	1669478400	1669478400	1669478400
```

The day value for the wrong event is pointing to _Friday 25. November 2022 23:00_ instead of _Saturday 26. November 2022 0:00_

I already set the setting for `[SYS][phpTimeZone] = Europe/Berlin`

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

yesterday I have finished the DayGeneratorService and today I have reached some goals for translation and Daylight saving times.

I have just pushed my work to typo3_11_compatibility branch. Please check that version.

Please update DB schema in Installtool, truncate the day table and save the records again.

Stefan

**Comment by PhilippKuhlmay** [comment]
This is now working. Thanks.
