### ISSUE TITLE
[TYPO3 11] disabled exceptions inside recurring event are still showing up 

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#345]
Hi I have an recurring event which had some exceptions. I disabled them but they are still showing up in the frontend. The event has the same settings as in #342. 
I already cleared all caches and updated the database schema as I tried to test the issue #342.
Code is already updated after your last commits this day.

<img width="1055" alt="Bildschirmfoto 2022-04-05 um 16 17 32" src="https://user-images.githubusercontent.com/57705869/161775055-ae9a0e56-9fea-4da8-bbea-dc01f3946375.png">

<img width="671" alt="Bildschirmfoto 2022-04-05 um 16 17 52" src="https://user-images.githubusercontent.com/57705869/161775166-7aea855a-6e5f-407f-b9c1-3c97e4cce71b.png">

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for your help. I have just uploaded a new version to typo3_11_compatibility. It also tests that hidden records will not be processed by DayGeneratorService.

Stefan
