### ISSUE TITLE
Location and organizer as optional parameter

### ISSUE THREAD

**Issue by wowawebdesign** [jweiland-net/events2#35]
At the moment, the location and the organizer of an event are required parameters, and the location is binded to maps2/Google Maps.

If both parameters would be optional, the events2 could be used without a google account.

**Comment by froemken** [comment]
Good point, as we have the idea to implement OpenStreetMap as well.

Information for me:
- Set maps2 as suggested in ext_emconf.php
- Change Templates to check, if location/organizer is set or not
- I need something in ExtConf to enable/disable autogenerating of maps2 records while saving locations.

**Comment by froemken** [comment]
Done.
