### ISSUE TITLE
Recurring event shows wrong detailed event

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#358]
Hi,

I have an recurring event each 4 weeks which starts at 07. March 2022. The detail page for all events shows the 07.03.2022 instead of the selected event.

<img width="1138" alt="Bildschirmfoto 2022-05-02 um 12 35 49" src="https://user-images.githubusercontent.com/57705869/166221641-7f53e6b2-62f6-47b6-9e5b-59cdce632393.png">

At the right it should be the 02. May 2022. The URL is correct and shows `URL/termine/details/2022-05-02/monatstreffen`

Even the iCal export has the wrong event inside.
---------

TYPO3 11.5.9
Events2 8.0.0

Cache cleared. DB schema updated. Upgrade Wizard executed. No own templates for the events.

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for your help. Currently I can't confirm this issue, but it could be that you haven't updated the RouteEnhancer. I have renamed nearly all Controllers and Plugins, so you have to update your configuration, too.
Please check, if RouteEnhancer relates to show instead of list plugin `tx_events2_show`

Following GET param has to be catched by RouteEnhancer:

tx_events2_show%5Btimestamp%5D=1653861600

Stefan

**Comment by froemken** [comment]
Found it!

You have removed hour (H) and minute (i) from RouteEnhancer configuration. They are mandatory to identify the correct time-record for given event:

Please re-add them as described here:

https://github.com/jweiland-net/events2/issues

Stefan

**Comment by PhilippKuhlmay** [comment]
Works now, thanks.

**Comment by sfroemkenjw** [comment]
Hello @loeffe1 

have you configured the scheduler task to update the day records?
Is the next possible date in range as configured in extension settings?

Stefan

**Comment by loeffe1** [comment]
Thanks for your reply, @sfroemkenjw 

Yes, the scheduler task is running and future dates will be generated for 6 months while the next upcoming date is next monday.

**Comment by loeffe1** [comment]
I found the problem. The date displayed in detail view was exactly 3 months in the past from the next future date. Turns out recurringPast was set to 3. Setting it to 0 fixed the incorrect date.

**Comment by sfroemkenjw** [comment]
Morning @loeffe1 

"How would I ensure that I can create past dates but still display the correct next future date?" this is the default behavior of events2. I don't get your described problem. But if setting recurringPast to 0 helps, hmm...OK.

If you have further questions I would prefer to create a new issue ticket.

Stefan

**Comment by loeffe1** [comment]
Hi @sfroemkenjw,
I tested this in a fresh TYPO3 installation and it is working as described and expected. Must be a bug in the configuration of that other project.
Thanks for your help and pointing me in the right direction!
