### ISSUE TITLE
[Feature Request] Recurring Events: Show actual description of single event beneath teaser and description for all events

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#363]
Hi,
I use TYPO3 10.4.27 and events2 7.1.3.
I work at a university of music where we have a lot of event series. Time, location, registration procedure and place are always the same, but the concert program details change for each event.
To simplify the editors' work as much as possible, I would like to work with recurring events, so that the general details only have to be specified once. The individual dates, defined as exceptions, should then contain the respective concert program details. 
As far as I understand events2, this is not possible at the moment, since the individual description is only ever added to the alternative dates.
I would be happy if events could also be used in the way I described.

Many greetings and thanks for the continuous development of the extension
Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

there is a ViewHelper in events2 for this special case:

```
<f:for each="{e2:getExceptionsFromEventForSpecificDate(event: day.event, date: day.day, type: 'info')}" as="exception">
	<br><em>{exception.exceptionDetails -> f:format.html(parseFuncTSPath: 'lib.parseFunc') -> f:format.nl2br()}</em>
</f:for>
```

Have a cool start into upcoming weekend

Stefan

**Comment by Hobokens** [comment]
Hello @froemken ,
I've seen that viewhelper. Maybe I misunderstand you, but when I use the viewhelper, I don't get the exceptions just for the actual event.
That's what I tried.
```
    <div itemprop="articleBody">
        {day.event.detailInformation -> f:format.html()}
        <f:for each="{e2:getExceptionsFromEventForSpecificDate(event: day.event, date: day.day, type: 'info')}"
               as="exception">
            <div>{exception.exceptionDetails -> f:format.html(parseFuncTSPath: 'lib.parseFunc')}</div>
        </f:for>
    </div>
```
Best regards
Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

I don't understand that. Events2 will only add exceptions of the same date given in VH:

https://github.com/jweiland-net/events2/blob/12219a4c94bec934956cc585fd0bfc7c4226b2f6/Classes/Domain/Model/Event.php#L437

Can you please add two f:debug entries for `{day.day}` and `{exception}` into your template for testing. IMO both dates (day.day and exception.exceptionDate) should be the same.

Stefan

**Comment by Hobokens** [comment]
Hello @froemken ,
I'm sorry, but I can't debug {exception}
```
        <f:for each="{e2:getExceptionsFromEventForSpecificDate(event: day.event, date: day.day, type: 'info')}"
               as="exception">
                <f:debug>{exception}</f:debug>
        </f:for>
```
I get no results. Even the black bar on top of the page (Extbase Variable Dump) is missing.

Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

if there is no output, then there are no exception records of type "Info" for this date configured in events2 record. As attribute "type" is registered as non-required, you can try to remove that and f:debug ALL exception records for a given date, regardless of their type.

Stefan

**Comment by Hobokens** [comment]
Hello @froemken ,
thanks for your help. Removing `type: 'info'` did the trick. Now I get the desired result:

```
        <f:for each="{e2:getExceptionsFromEventForSpecificDate(event: day.event, date: day.day)}"
               as="exception">
            {exception.exceptionDetails -> f:format.html()}
        </f:for>
```

Hobokens
