### ISSUE TITLE
Error after update from 7.1.3 to 8.0.1 (TYPO3 10.4.28)

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#366]
Hi,
after the update of events2 from v7.1.3 to v8.0.1 (TYPO3 v10.4.28) and clicking the flush cache button in installtool afterwards, I'm getting this error:

No Content Object definition found at TypoScript object path "tt_content.list.20.events2_search"
More information regarding this error might be available [online](https://typo3.org/go/exception/CMS/1540246570).

Can you help me with this issue?

Best regards
TJ

**Comment by derBoogie** [comment]
After running the Upgrade Wizard, the error has gone.

**Comment by froemken** [comment]
Hello @derBoogie 

right, TYPO3 has deprecated the switchableControllerActions mechanism. I understand the problem with that, but I hate it at the same time ;-)
I really tried to make the upgrade process as easy as possible, but yes, upgrading to 8.0.0 is much harder than normal:

https://docs.typo3.org/p/jweiland/events2/8.0/en-us/AdministratorManual/Upgrade/Index.html#new-plugins

Have a cool start into this week.

Stefan
