### ISSUE TITLE
[QUESTION] Scheduler job "Re-Create day records" 

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#368]
After the update to Events2 version 8.0.1 I had trouble with the display of events.
1. Events copied as a template showed the date of the template after the date was changed.
2. The publishing date did not work - the events were not displayed even though the publishing date had already passed.
Only after the setup of the scheduler job "Re-Create day records" problems disappeared.

So my question is if the display of the dates only works properly with the scheduler job?

Regards TJ

**Comment by froemken** [comment]
Hello @derBoogie 

Question 1:
Copying records were processed in method process_cmdmap() of DataHandler while inserting/updating new records were processed in process_datamap() of DataHandler. As events2 only connects to hooks in process_datamap() it does not get an information about a copied or versioned record. So, yes, in that case you have two options:

* Just open the new copied record and save it
* Execute the scheduler task to re-create the day records.

Question 2:
I have to test that. No time currently.

Last Question:
Saving an event2 record will delete all related day records and creates them new. So it should not "only" work with the scheduler task.

Stefan

**Comment by derBoogie** [comment]
Hi @froemken

thank you very much for your explanations.
I will monitor the behavior and report if the problems occur again.

Regards
TJ

**Comment by derBoogie** [comment]
Hi @froemken 

I was able to narrow down my problem further. It only occurs when you create a new event or copy one as an editor and not as an admin. The event is not showing then. If I switch to the admin account and open and save the event, it is then displayed. The scheduler task to re-create the day records runs every 10 minutes, but does not solve the problem - the event is still not showing.

Can you please try to reproduce the behavior?

Regards
TJ

**Comment by froemken** [comment]
Hello @derBoogie 

TYPO3 does very nasty stuff with translated records which will lead to duplicate created records. I have prevent such duplicates in my code, but it need sys_language_uid to be a valid column for editors. Please add that column to access rights and it should work.

Stefan

**Comment by derBoogie** [comment]
Hi @froemken 

you first have to come up with that!

sys_language_uid is hidden for editors on my sites because there is only the default language.
As suggested, I added sys_language_uid to access rights of the usergroup.
Now the changes are applied immediately - as it should be =)

Thanks a lot for solving the problem!

Regards
TJ
