### ISSUE TITLE
Keine strukturierten Daten (Json) mehr 

### ISSUE THREAD

**Issue by Mikel2411** [jweiland-net/events2#369]
Hat es eine bestimmten Grund warum die strukturierten Daten im letzten Release nicht mehr eingebunden wurden?
Die Datei JWeiland\Events2\Service\JsonLdService ist noch verhanden aber nicht mehr im DayController eingebunden.

**Comment by SvenJuergens** [comment]
@Mikel2411 Welche Version von events2 nutzt du? 
in der 7er Version hatte ich zwischendurch das Problem, das die Daten in der SingleView nicht mehr ausgegeben wurden.
In der 8ter sollte es aber wieder laufen

**Comment by froemken** [comment]
Ich kann das Problem derzeit weder in der 7.1.3 noch in der 8.1.0 nachvollziehen.
Bin mir aber auch sicher, das mal vor ein paar Monaten bereits gelöst zu haben. Hatte IMO nen EventListener vergessen zu registrieren.

Ich schließe das Ticket mal.
