### ISSUE TITLE
iCal download not working any more after update to 8.0.1

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#370]
Hi,

the iCal download isn't working anymore after the update to version 8.0.1

Here is an example event: https://www.wiesbaden-schelmengraben.de/event/22-07-2022_18.00/architek-tour-durch-den-schelmengraben-2-termin

And the iCal download link for this event: https://www.wiesbaden-schelmengraben.de/event?tx_events2_show%5Baction%5D=download&tx_events2_show%5Bcontroller%5D=ICal&tx_events2_show%5BdayUid%5D=614047&cHash=efd37e92481ef59941ce62ce8a0aad9b

For testing, I put a custom logger inside the downloadAction of ICalController, but the action is not called and no logging entry is generated.

Here is my iCalendar section in Partials/Day/Properties.html

```
<f:section name="iCalendar">
<div class="event-detail-row">
	<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
	<f:link.action action="download" controller="ICal" target="_blank" arguments="{dayUid: day.uid}">
		{f:translate(key: 'export')}
	</f:link.action>
</div>
</f:section> 
```

regards TJ

**Comment by froemken** [comment]
Hi @derBoogie 

this is not a problem of events2. Thank you for your links where I can test that.

After opening such a link, my browser was immediately redirected by a 307 status code. So, please check your .htaccess or entries in redirects module.

Stefan

**Comment by derBoogie** [comment]
Hi @froemken,

thanks for the redirection hint.

I have a redirect from "/event" to events-overview because "event" that is the name of the event-details page - this is the problem.
Now Iv'e adjusted my regexp so that it only forwards if no query parameters are present.

```
RewriteCond %{HTTP_HOST} ^www\.mydomain\.de$
RewriteCond %{QUERY_STRING} ^$
RewriteRule ^event\/?$ /veranstaltungen-und-termine [L,R=302]
```

The iCal download works now =)

Is there a routeEnhancers pattern for the iCal downloads link?

Regards
TJ
