### ISSUE TITLE
routeEnhancer Example not working in v8.0.1

### ISSUE THREAD

**Issue by rweymann** [jweiland-net/events2#372]
I copy/pasted the example of routeEnhancer from Classes/Routing/Aspect/TimestampMapper.php and it worked in v7.0.1
I made an update to v8.0.1 (also tried v8.0.0), but the config doesn't work anymore. 

Events2ShowPlugin:
    type: Extbase
    extension: Events2
    plugin: Events
    routes:
      -
        routePath: '/show/{date}/{event_title}'
        _controller: 'Day::show'
        _arguments:
          date: timestamp
          event_title: event
    requirements:
      date: '\d{4,4}-\d{2,2}-\d{2,2}_\d{4,4}'
      event_title: '^[a-zA-Z0-9\-]+$'
    defaultController: 'Day::show'
    aspects:
      date:
        type: TimestampMapper
        format: 'Y-m-d_Hi'
      event_title:
        type: PersistedAliasMapper
        tableName: tx_events2_domain_model_event
        routeFieldName: path_segment

**Comment by stephanweigelt** [comment]
I had the same problem and could solve it a few minutes ago: change the plugin name to 'list' (line 4 of your example-code).

Events2ShowPlugin:
type: Extbase
extension: Events2
plugin: list
...

**Comment by rweymann** [comment]
> I had the same problem and could solve it a few minutes ago: change the plugin name to 'list' (line 4 of your example-code).
> 
> Events2ShowPlugin: type: Extbase extension: Events2 plugin: list ...

Thanks for pushing me into the correct direction. I needed to change plugin to "show". I found the relevant names to be found in https://github.com/jweiland-net/events2/blob/master/Configuration/TSconfig/ContentElementWizard.tsconfig being the second string of list_type.

**Comment by froemken** [comment]
Hello @rweymann 

thank you for that issue. Yeah, that was damn hard work to manage/re-structure all these events2 plugin for TYPO3 11. And yes, I get confused sometime, too ;-)

I have created a PR for that issue:
https://github.com/jweiland-net/events2/pull/375/files

Is that OK for you?

Stefan
