### ISSUE TITLE
Country table not filled

### ISSUE THREAD

**Issue by ZeEmEs** [jweiland-net/events2#382]
On an older setup the static tables (e.g. static_countries) were filled with default values. Now they are empty.

Tested on a MySQL/Maria and PostgreSQL DB setup with the composer installation.

And only with the PostgreSQL DB there is an SQL Error while saving an event location without a selected country. Probable difference to MySQL/MariaDB is that an empty string cannot be written to an integer DB field in PostgeSQL, whereas in MySQL it is converted to 0.

**Comment by froemken** [comment]
Hello @ZeEmEs 

With PR https://github.com/jweiland-net/events2/pull/387 I have changed the return value of getCountry() to integer. That way the default value in TCA of country can not be an empty string anymore.
I have just merged the PR to master. Feel free to test that version. Reopen the issue ticket if the bug still exists.

Thank you for your support

Stefan
