### ISSUE TITLE
Events2PageTitleProvider only works on detail plugin

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#384]
The page title provider `Events2PageTitleProvider` only works when using the detail plugin. If the list plugin is used (which is allowed to show the show action as well), it doesn't work.

I propose to either:
- check both arguments
- add a note to the docs

**Comment by froemken** [comment]
Hi @georgringer 

I have just pushed a compatible version for list and detail version to master: #386
The next maintenance version will contain the bugfix

Have a nice start into the upcoming weekend

Stefan
