### ISSUE TITLE
Bilder in Listen-Ansicht

### ISSUE THREAD

**Issue by d3werk** [jweiland-net/events2#385]
Moin moin,

habt Ihr in eurer Timeline es mal vorgesehen, dass auch Bilder in der Listen-Ansicht erscheinen?

VG
d3werker

**Comment by froemken** [comment]
Moin @d3werk 

klaro. Haben wir hier zum Beispiel schon umgesetzt:

https://www.pforzheim.de/veranstaltungen.html?tx_events2_events%5Baction%5D=list&tx_events2_events%5Bcontroller%5D=Day

Auch im Template habe ich bereits eine Erleichterung eingebaut:
https://github.com/jweiland-net/events2/blob/master/Resources/Private/Partials/Event/List.html#L78-L98

Du brauchst in Deinem eigenen Event/List Partial nur noch diesen Einzeiler hinzuzufügen:
`<f:render section="firstImage" arguments="{event: day.event}" />`

Schönen Start ins Wochenende

Stefan

**Comment by d3werk** [comment]
Moin Stefan,

 

vielen Dank für die schnelle Antwort 😉 super cool.

 

 

 

 

 

Beste Grüße und Dir auch einen schönen Start ins Wochenende…

Christian Dräger

 

 



 

Schützenstr. 6

21271 Asendorf

 

Fon:    04183/ 774841

Mobil:  0162/ 9827010

Web:    <http://www.d3-werk.de/> http://www.d3-werk.de

 

 <https://www.xing.com/profile/Christian_Draeger11/cv>    <https://www.linkedin.com/in/christian-dr%C3%A4ger-473b0653/>    <https://www.facebook.com/d3werker> 

 

Steuer-Nr.: 50/ 110/ 02884

 

Diese e-Mail und alle Anhänge sind vertraulich und nur für den Adressaten bestimmt. Sie können rechtlich geschützte Nachrichten enthalten und dürfen anderen Personen nicht offenbart werden. Im Falle von Fehlleitungen wird der Empfänger gebeten, den Absender umgehend zu unterrichten und die e-Mail nebst Anhängen zu löschen.

This e-mail and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. They may contain legally privileged information, and may not be disclosed to anyone else. If you have received this e-mail in error, please notify the sender and delete all copies from your system.

 

Von: Stefan Frömken ***@***.***> 
Gesendet: Freitag, 18. November 2022 09:32
An: jweiland-net/events2 ***@***.***>
Cc: d3werker ***@***.***>; Mention ***@***.***>
Betreff: Re: [jweiland-net/events2] Bilder in Listen-Ansicht (Issue #385)

 

Moin @d3werk <https://github.com/d3werk> 

klaro. Haben wir hier zum Beispiel schon umgesetzt:

https://www.pforzheim.de/veranstaltungen.html?tx_events2_events%5Baction%5D=list <https://www.pforzheim.de/veranstaltungen.html?tx_events2_events%5Baction%5D=list&tx_events2_events%5Bcontroller%5D=Day> &tx_events2_events%5Bcontroller%5D=Day

Auch im Template habe ich bereits eine Erleichterung eingebaut:
https://github.com/jweiland-net/events2/blob/master/Resources/Private/Partials/Event/List.html#L78-L98

Du brauchst in Deinem eigenen Event/List Partial nur noch diesen Einzeiler hinzuzufügen:
<f:render section="firstImage" arguments="{event: day.event}" />

Schönen Start ins Wochenende

Stefan

**Comment by froemken** [comment]
Moin @d3werk 

Du hast das Ticket aus der Mail heraus beantwortet, richtig?
Klick mal auf diesen Link: https://github.com/jweiland-net/events2/issues/385
In Deiner Antwort ist alles drinne, von zig Leerzeilen, Footer, Telefonnummern, Alles.

Nur ein freundlicher Hinweis, den Beitrag mal eben online zu bearbeiten ;-)

Schönen Start ins Wochenende
