### ISSUE TITLE
Fatal error 'compatibility to solr 11'

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#390]
Hi,
TYPO3 10.4.32, solr 11.2., events2 8.1.2 

After upgrading to events2 v8.1.2 I get the following fatal error:

`Fatal error: Declaration of JWeiland\Events2\Hooks\Solr\IndexerHook::modifyDocuments(ApacheSolrForTypo3\Solr\IndexQueue\Item $item, int $language, array $documents): array must be compatible with ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerDocumentsModifier::modifyDocuments(ApacheSolrForTypo3\Solr\IndexQueue\Item $item, $language, array $documents) in /var/www/vhosts/xxxxx.my-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/events2/Classes/Hooks/Solr/IndexerHook.php on line 44`

Rebuild PHP Autoload Information throws an error and can't clear the cache in install tool.

**Comment by froemken** [comment]
Hi @Hobokens 

they have changed the Interface from 11.2 to 11.5.
I have copied the IndexerHook and made it solr 11.2 compatible.
Please give events2 8.1.4 a try.

Thank you for your report

Stefan

**Comment by Hobokens** [comment]
Thank you @froemken for the fast bugfix. It solved the problem for me.

Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

with my last patch I have set IndexerHook and IndexerHook104 as public which should solve this issue. In case of standalone/legacy TYPO3 installations it seems that the DI cache was not build from scratch while updating an extension.

Please visit Installtool and click on "Flush cache" or remove the directory `typo3temp/var(cache/code/di` and reload the page. That will rebuild the DI cache.

Please leave a note, if that works for you.

Stefan
