### ISSUE TITLE
Optional JsonLdService in TS constants

### ISSUE THREAD

**Issue by the-robman** [jweiland-net/events2#395]
Would it be possible to add an extra parameter in the Typoscript constants for the function "addJsonLdToPageHeader" in JWeiland\Events2\Service\JsonLdService ?

Maybe like so:
```code
plugin.tx_events2.settings.addJsonLdToPageHeader = 1 yes / 0 no
```
```php
if ($this->settings['addJsonLdToPageHeader']) ...
```
The reason is, that I write the json schema directly in the fluid template (list view) with several extra structured data properties and want to write the same in the detail view of an event.

**Comment by sfroemkenjw** [comment]
Hello @the-robman 

interesting request. I'm pretty sure we will not implement that in near future.
Please have a look in overriding EventListeners:
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Events/EventDispatcher/Index.html#overriding-event-listeners

So you can write your own EventListener and overwride my EventListener with identifier: `addJsonLdToPageHeader`. That way you can deactivate my solution.

Stefan
