### ISSUE TITLE
Can't access {image.description} in Fluid Template

### ISSUE THREAD

**Issue by maslme** [jweiland-net/events2#400]
I want to display the image description as set in the TYPO3 Backend in the frontend - but in the partial Event/List.html in the section "firstImage" the {image.description} is always NULL.

**Comment by SvenJuergens** [comment]
@maslme hi, for images in TYPO3 you can use this notation
 {image.originalResource.description} or {image.originalResource.alternative}
so you can query the info in other extensions as well.
What I haven't figured out yet is why the shorthand sometimes works and sometimes not.

**Comment by froemken** [comment]
In Extbase images are of type Extbase\Domain\Model\FileReference. It does not have description property. You have to call originalResource first (see answer of Sven).

@SvenJuergens 
Please use f:debug on image property. If type is Extbase\Domain\Model\FileReference call originalResource first. If type is Core\Resource\FileReference you can use description property directly.

**Comment by maslme** [comment]
Thanks for the hints and the explanation. Thought there was something wrong, because when I debugged the {image} i couldn't pull out the originalResource as sometimes.
Now it's working.
