### ISSUE TITLE
Event List Sort

### ISSUE THREAD

**Issue by nergerf** [jweiland-net/events2#401]
How can I sort the list view by event end date?

Thanks
Frank

**Comment by sfroemkenjw** [comment]
Hello @nergerf 

In TYPO3 BE: Please click on the title of the table to enter the single table view. Add column event_end. Click on the title of the column event end to sort events.

For TYPO3 FE:
There is no possibility to sort the records as editor or integrator by TS or fluid template. But as a developer you can create an EventListener to nearly all queries made in DayRepository. Have a look into findEvents(). At the bottom you will find:

```
ModifyQueriesOfFindEventsEvent($queryBuilder, $subQueryBuilder, $type, $filter, $this->settings)
```

With an EventListener you can modify the QueryBuilder object

Have a nice start into the weekend

Stefan

**Comment by nergerf** [comment]
Hello
Thanks for your answer.
I solved it in my own List.html template with the following query.
<f:for each="{days->v:iterator.sort(order: 'ASC', sortBy: 'event.eventEnd')}" as="day" iteration="iterator">
</f:for>
It works.
