### ISSUE TITLE
503 error when calling the scheduler

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#402]
After the update to TYPO3 11.5 and Events2 8.1.5 I'm getting an 503 error, when calling the Scheduler in backend:

Typed property JWeiland\Events2\Configuration\ExtConf::$defaultCountry must be int, string used

Unfortunately, I can't see in which file the error can be corrected.

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

have you read the Upgrade instructions?

For 7.0.0 you have to delete and re-create the scheduler task:
https://docs.typo3.org/p/jweiland/events2/main/en-us/AdministratorManual/Upgrade/Index.html#upgrade-to-version-7-0-0

I'm closing this issue for now. Feel free to re-open it, if you have further information for us.

Stefan

**Comment by derBoogie** [comment]
Hey @sfroemkenjw 

thank you for the hint!

After deleting the old scheduler task and recreateing the same again, the error is gone =)

TJ
