### ISSUE TITLE
[Feature Request] add resetButton to Litepicker config

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#403]
Please add the reset button to Litepicker config by default because there is no possibility to clear the date input fields.

Events.js :

me.initializeDatePicker = function () {
	document.querySelectorAll('.addDatePicker').forEach($inputWithDatePicker => {
		new Litepicker({
			element: $inputWithDatePicker,
			format: me.dateFormat,
			singleMode: true,
			resetButton: true
		});
	});
};

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

sorry, I can not confirm that issue in `events2` 8.1.5. I have that "remove" button:

<img width="498" alt="Bildschirm­foto 2023-02-23 um 09 52 23" src="https://user-images.githubusercontent.com/123929835/220860983-06e899b9-7233-49ba-b747-32b6a1c9d2e9.png">

Further I can not find `me.initializeDatePicker` in full code of `events2`

I'm closing this issue for now. Feel free to re-open that issue if you have further information for us.

Stefan

**Comment by derBoogie** [comment]
@sfroemkenjw 

the Litepicker looks different on my site, as you can see in the screenshot:

![Screenshot-Events2-Litepicker](https://user-images.githubusercontent.com/1611217/220877338-898e02c4-96b8-47a5-8843-9aa1bb4d3ecd.jpg)

TJ

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

OK thank you. You are using the extbase form instead of the new EXT:form implementation. That's the difference.

I have just merged that line to dev-main.

Don't know when I will release a new version. Maybe tomorrow...

Stefan

**Comment by derBoogie** [comment]
Hi @sfroemkenjw

thank you for the explanation.

I will update as soon as you have released the new version.

TJ

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

I have just released version 8.1.6

Stefan

**Comment by derBoogie** [comment]
Hi @sfroemkenjw

thank's for the new version 8.1.6.
I've just installed it, cleared all caches, but the date fields shows still the Litepicker:
 
![Litepicker-Events2](https://user-images.githubusercontent.com/1611217/222969382-43c963ee-14e0-40e7-9453-14fa2149ab1a.jpg)

TJ

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

don't understand "but the date fields shows still the Litepicker".
The LitePicker is the new VanillaJS based DatePicker, replaces the old jquery-ui DatePicker and it contains the reset button now. So, currently I don't get the problem.

But yes: If you make use of the "old" Extbase based create form you still have the jquery-ui DatePicker. I have forgotten to remove jquery there. That's why search form and create form look different.

Stefan
