### ISSUE TITLE
[Feature Request] Litepicker set language

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#404]
The Litepicker is in English language by default.
To change the language, it's necessary to set the "lang" option on initialization:

Events2.js:

```
me.initializeDatePicker = function () {
	document.querySelectorAll('.addDatePicker').forEach($inputWithDatePicker => {
		new Litepicker({
			element: $inputWithDatePicker,
			format: me.dateFormat,
			singleMode: true,
			resetButton: true,
			lang: 'de-DE'
		});
	});
};
```

**Comment by derBoogie** [comment]
Hi @sfroemkenjw 

the Litepicker looks different on my site:

![Screenshot-Events2-Litepicker](https://user-images.githubusercontent.com/1611217/220876284-5b784013-2d27-4c64-b39b-9273e5b25cef.jpg)

And here is a screenshot of the installed Events2 Version (8.1.5) and the Events2.js file with me.initializeDatePicker:

![Screenshot-Events2-8 1 5](https://user-images.githubusercontent.com/1611217/220876557-e8a2633e-11dc-42b2-96b9-77f3a33d2c69.jpg)

TJ

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

now I can confirm your issue. You're using the extbase form to insert new events. I instead use the new EXT:form integration of events2 (configurable in TS constants) where another DatePicker will be used.

Just a note for the developer who will work on that:
We can not just apply a hard-coded ISO code to JS. Configure that value with TS:settings is also a bad idea. Maybe we can extract the ISO code from SiteConfiguration and make it available in a data attribute in Template/Layout.

Stefan
