### ISSUE TITLE
Don't show Translation of detail-view-page if event is not translated 

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#410]
I have a website with two languages, DE / EN.

If an event is not translated to EN it's necessary to hide the "EN-link" in the language menu in the detail-view page.

This is how the langugae menu is rendered:
```

page.1 = FLUIDTEMPLATE
page {
	1.dataProcessing {
		40 = TYPO3\CMS\Frontend\DataProcessing\LanguageMenuProcessor
		40 {
			languages = 0,1
			as = languagemenu
		}
	}
}
```

Is there a way to tell the LanguageMenuProcessor to hide the translation-links on the event detail-view page, if the event is not translated?

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

IMO that's more a TYPO3 related question. As you see in your TS the LanguageMenuProcessor is related to page context and not content context.

I would prefer to ask that question somewhere in the TYPO3 Slack channel.

Stefan
