### ISSUE TITLE
Error with TYPO3 11.5.26: The ColumnMap for property "tx_events2_domain_model_exception"  ...

### ISSUE THREAD

**Issue by SvenJuergens** [jweiland-net/events2#411]
"tx_events2_domain_model_exception" of class "JWeiland\Events2\Domain\Model\Exception" is missing.

@froemken 
Seems this [patch](https://github.com/TYPO3/typo3/commit/30a93ac88a85066ee12c2730dd9d74847ee252a1) from TYPO3 11.5.26 and the using of this [line](https://github.com/jweiland-net/events2/blob/cf934d72393668beda92343037a16657e23f6e12/Configuration/TCA/tx_events2_domain_model_event.php#L538) result in an error:
with `'foreign_default_sortby' => 'exception_date ASC',` seems to work (but not fully testet).

is this an Regression in TYPO3 or an bug in events2 (8.1.6)?

Best Regards
Sven

**Comment by lukas-makes-code** [comment]
I can confirm this behavior as well!

**Comment by ktallafus** [comment]
Same here
