### ISSUE TITLE
widget.iCalendar error

### ISSUE THREAD

**Issue by weiseger** [jweiland-net/events2#414]
Got this error:
Fluid parse error in template partial_Day/Properties_a97152f827542b134024f4789f6d30ead2899e84, line 186 at character 5. Error: The ViewHelper "<e2:widget.iCalendar>" could not be resolved. Based on your spelling, the system would load the class "JWeiland\Events2\ViewHelpers\Widget\ICalendarViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <e2:widget.iCalendar day="{day}" />

I run TYPO3 11.5.26 and Events2 8.1.5
Server Settings:
Webserver: Apache
PHP-Version: 8.2.4
Datenbank (Default): MySQL 10.2.36-MariaDB-log
Anwendungskontext: Production
Composer-Modus: Aktiviert
Betriebssystem: Linux 5.15.80

Got a clue to fix it?

**Comment by SvenJuergens** [comment]
@weiseger hello can it be that you have made an update?
If so, check [here](https://docs.typo3.org/p/jweiland/events2/main/en-us/AdministratorManual/Upgrade/Index.html#fluid-widget-replacement) if these upgrade instructions can help you solve your problem.

**Comment by sfroemkenjw** [comment]
Thank you @SvenJuergens 

you're right. This widget has been replaced and @weiseger has to update his templates like described in your link.

Stefan
