### ISSUE TITLE
After Update Error in Cron: IndexerRunner::__construct()

### ISSUE THREAD

**Issue by fischhase** [jweiland-net/events2#418]
Dear Contributors,
after updating the ext ke_search I get an error message at running the cron scheduler:run:

Uncaught TYPO3 Exception Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 1 passed in /usr/www/users/XXX/typo3/typo3_src-11.5.26/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3249 and exactly 2 expected
thrown in file /usr/www/users/XXX/web/domain.de/typo3conf/ext/ke_search/Classes/Indexer/IndexerRunner.php
in line 93

Subject of the TYPO3 schedular error mail is: Cron <xxx@xxx> '/usr/bin/flock' -n -E 0 '/usr/home/xxx/.tmp/3f36cb8d8d9e65f5ab10ffcc8f6f8224.lck' '/bin/bash' -c '/usr/bin/php74 /usr/www/users/xxx/web/domain.de/typo3/sysext/core/bin/typo3 scheduler:run'

Opening the Schedular Module, the error message appears:
Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 1 passed in /usr/www/users/xxx/typo3/typo3_src-11.5.26/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3249 and exactly 2 expected

Hope you know a solution. Thank you

**Comment by SvenJuergens** [comment]
hi @fischhase  just from reading your post and the error messages, why do you think it has something to do with the events2 extension and not the ke_search extension?

**Comment by SvenJuergens** [comment]
@fischhase think this is not a problem, can happen.
Then you might like to close the Issue?
