### ISSUE TITLE
TYPO3 12.4 Compatible Version

### ISSUE THREAD

**Issue by devtroll** [jweiland-net/events2#419]
Is there any information yet when this extension will be available for TYPO3 v12?

Greetings

**Comment by sfroemkenjw** [comment]
Hello @devtroll 

First of all: Yes, events2 will be TYPO3 12 compatible.
But for now we just have a hand full of customers upgrading to TYPO3 12 where events2 ist not needed. So, it does not have any prio for us.
As many community members are working with events2 in relation to maps2, maps2 has to be upgraded first. That job is already in my requested line of our kanban board.

I'm just the developer and not the projectmanager, but I'm pretty sure that nothing will happen here within the next 2 months.

Stefan

**Comment by mdahms** [comment]
Hi Stefan,

Is there any new information yet? We would also like to update our systems.

Best regards
Matthias

**Comment by sfroemkenjw** [comment]
Just for your information. There is already a typo3_12_compatibility branch available where I have just done a plain upgrade:

https://github.com/jweiland-net/events2/tree/typo3_12_compatibility

Same issues, same bugs, no test upgrades. Please download as ZIP or implement it in composer with `dev-typo3_12_compatibility`

Stefan

**Comment by sfroemkenjw** [comment]
Yehaaa. We have just release events2 9.0.0 for TYPO3 12.
