### ISSUE TITLE
Typo3 Planned Tasks - Tagessätze Neu Erstellen 503

### ISSUE THREAD

**Issue by Blaster-1024** [jweiland-net/events2#422]
Im Planer kommt es zu einem 503 Fehler beim Aufruf die Events neu einzulesen.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getCache() on null | Error thrown in file /html/typo3/typo3conf/ext/events2/Classes/Task/ReGenerateDays.php in line 77. Requested URL: https://event.dart-merseburg.de/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&CMD=setNextExecutionTime&tx_scheduler[uid]=2

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getCache() on null | Error thrown in file /html/typo3/typo3conf/ext/events2/Classes/Task/ReGenerateDays.php in line 77. Requested URL: https://event.dart-merseburg.de/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&CMD=toggleHidden&tx_scheduler[uid]=2 

Muss ich es vorher als Aufgabe importieren lassen? Und wenn ja, wie finde ich den Import.xml Pfad heraus?

**Comment by Blaster-1024** [comment]
2.Problem
 Die Detailansicht wird nicht richtig ausgegeben. 
 Prinzipell scheint die Weiterleitung zu stimmen (Die Überschrift ist Hidden, so wie in der Deteilansicht gewollt.) Nur leider wird das selbe wie in der Hauptseite ausgegeben.

**Comment by Blaster-1024** [comment]
> Im Planer kommt es zu einem 503 Fehler beim Aufruf die Events neu einzulesen.
> 
> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getCache() on null | Error thrown in file /html/typo3/typo3conf/ext/events2/Classes/Task/ReGenerateDays.php in line 77. Requested URL: [https://event.dart-merseburg.de/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&CMD=setNextExecutionTime&tx_scheduler[uid]=2](https://event.dart-merseburg.de/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&CMD=setNextExecutionTime&tx_scheduler%5Buid%5D=2)
> 
> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getCache() on null | Error thrown in file /html/typo3/typo3conf/ext/events2/Classes/Task/ReGenerateDays.php in line 77. Requested URL: [https://event.dart-merseburg.de/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&CMD=toggleHidden&tx_scheduler[uid]=2](https://event.dart-merseburg.de/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&CMD=toggleHidden&tx_scheduler%5Buid%5D=2)
> 
> Muss ich es vorher als Aufgabe importieren lassen? Und wenn ja, wie finde ich den Import.xml Pfad heraus?

**Comment by sfroemkenjw** [comment]
Hello @Blaster-1024 

with version 7.0.0 you need to remove and add the scheduler task of events2 again:
https://docs.typo3.org/p/jweiland/events2/main/en-us/AdministratorManual/Upgrade/Index.html#upgrade-to-version-7-0-0

Stefan

**Comment by Blaster-1024** [comment]
503 Fehler Weg, aber auch meine Daten. Egal. Trotzedem Vielen Dank für den TIP! 
Dieses Problem ist erledigt. Bleibt nur noch das mit der Falschausgabe der Details Seite.
