### ISSUE TITLE
[FEATURE REQUEST] Pagebrowser with pagenumbers

### ISSUE THREAD

**Issue by icehawk-de** [jweiland-net/events2#423]
Is it possible to add a pagebrowser with page numbers? <1 2 ... 5 6 >
The actual: next, previous, last, first istn't the best pagebrowser.

**Comment by SvenJuergens** [comment]
hi @icehawk-de, please have a look on the last version 8.2.0
https://docs.typo3.org/p/jweiland/events2/main/en-us/AdministratorManual/Pagination/Index.html

**Comment by sfroemkenjw** [comment]
Wow...nice. Community helps Community :-)

@SvenJuergens is right. I have simplified alternative pagination in events2 8.2.0 a lot. Thank you for posting the link to documentation.

Have a nice start in to this new week.

Stefan

**Comment by icehawk-de** [comment]
There is an error in the doku:
.settings. is missing!

Wong:
plugin.tx_events2.pageBrowser.class = GeorgRinger\NumberedPagination\NumberedPagination

Right:
plugin.tx_events2.settings.pageBrowser.class = GeorgRinger\NumberedPagination\NumberedPagination

**Comment by sfroemkenjw** [comment]
Hello @icehawk-de 

thank you for that information. I have pushed a new version:
https://github.com/jweiland-net/events2/pull/424

Should be available within the next 10 minutes at TYPO3 docs, too.

Stefan
