### ISSUE TITLE
ICS Files not valid (missing DTSTAMP property, Lines not delimited)

### ISSUE THREAD

**Issue by biedert** [jweiland-net/events2#426]
To ensure the validity of the downloaded ics files, a DTSTAMP property is necessary. See https://icalendar.org/iCalendar-RFC-5545/3-6-1-event-component.html

Furthermore, lines in an ics file should not be longer than 75 octets, which will be exceeded if a longer event title is given. Therefore, lines should be delimited by CRLF sequence. See https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html

Validation results taken from https://icalendar.org/validator.html

**Comment by sfroemkenjw** [comment]
Hello @biedert 

I have just released version 8.2.1 which will respect ical format while export/download.

Nice greetings

Stefan

**Comment by biedert** [comment]
Thank you @sfroemkenjw! Just updated and can confirm that the ICS file is valid now.
