### ISSUE TITLE
File-Upload restricted to 3 files

### ISSUE THREAD

**Issue by icehawk-de** [jweiland-net/events2#429]
The fileupload is restricted to max 3 files.

Found in: EXT:events2/Configuration/TCA/tx_events2_domain_model_event.php

```
'download_links' => [
    'exclude' => true,
    'label' => 'LLL:EXT:events2/Resources/Private/Language/locallang_db.xlf:tx_events2_domain_model_event.download_links',
    'config' => [
        'type' => 'inline',
        'foreign_table' => 'tx_events2_domain_model_link',
        'maxitems' => 3,
        'minitems' => 0,
        'appearance' => [
            'levelLinksPosition' => 'both',
            'newRecordLinkAddTitle' => true,
            'showSynchronizationLink' => 1,
            'showPossibleLocalizationRecords' => 1,
            'showAllLocalizationLink' => 1,
        ],
        'default' => 0,
    ]
],
```

Is there an easy way to increase the maxitems?

**Comment by sfroemkenjw** [comment]
Hello @icehawk-de 

please create or edit file `Configuration/TCA/tx_events2_domain_model_event.php` in your site package extension and add following line:

`$GLOBALS['TCA']['tx_events2_domain_model_event']['columns']['download_links']['config']['maxitems'] = 3265;`
