### ISSUE TITLE
Simultaneous usage of sDEF and sDEFAULT

### ISSUE THREAD

**Issue by loeffe1** [jweiland-net/events2#440]
I am trying to understand, why the events2MoveFlexFormFields upgrade wizard moves flexform configuration from the sDEFAULT sheet to sDEF, while the included flexforms are using the sDEFAULT sheet.

I am facing the issue where my migrated plugin settings are being stored in sDEF while the plugin is looking for those settings in sDEFAULT.

I am using v8.3.1

**Comment by sfroemkenjw** [comment]
Hello @loeffe1 

thank you for that hint. I have changed everything to `sDEF` now in FlexForms. Please update events2 and execute the UpgradeWizard

Stefan
