### ISSUE TITLE
Exception Serialization of 'Closure' is not allowed (Scheduler)

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/events2#449]
I got the Error "Serialization of 'Closure' is not allowed" when creating the "Re-create day records" task in TYPO3 12.4.9.
![2024-01-23_15-31-07](https://github.com/jweiland-net/events2/assets/343511/ae2eb45f-a6c1-4862-b826-e1f601ec12a4)

**Comment by sfroemkenjw** [comment]
Hi @wowaTYPO3 

thank you for that issue. I will release version 9.0.1 today

Stefan
