### ISSUE TITLE
search does't work

### ISSUE THREAD

**Issue by blueamerican** [jweiland-net/events2#45]
TYPO3 8.7.19
events 2.3.0

in the constant editor i have determined the necessary PIDS.

on my search page i have chosen the search plugin.

But i do not get a result.
Not even "Heute keine Veranstaltungen."
Only the search page is loaded again.

What is wrong here? Must i have a list view somewhere?

**Comment by blueamerican** [comment]
![search](https://user-images.githubusercontent.com/5647051/47599484-60b85f00-d9af-11e8-8e51-c24fa233bfd1.jpg)

**Comment by froemken** [comment]
Good morning @blueamerican 

yes, the search plugin transfers all parameters to a list plugin. See it in action here:

http://www.pforzheim.de/kultur-freizeit/veranstaltungen.html

That way you can have search plugin in right column, but results will be shown in center column.

Have a good start into the new week

Stefan

**Comment by froemken** [comment]
No response. Problem seems to be solved. Closing
