### ISSUE TITLE
Installing Could not Error when installing: class: "JWeiland\Maps2\Utility\GeocodeUtility" maybe not loaded or no autoloader? 

### ISSUE THREAD

**Issue by blueamerican** [jweiland-net/events2#46]
TYPO3 7.6.18
events 2.1.0

error when installing:
Could not analyse class: "JWeiland\Maps2\Utility\GeocodeUtility" maybe not loaded or no autoloader? Class JWeiland\Maps2\Utility\GeocodeUtility does not exist 

TYPO3 8.7.9
events 2.2.5
the same error:
Exception
Could not analyse class: "JWeiland\Maps2\Utility\GeocodeUtility" maybe not loaded or no autoloader? Class JWeiland\Maps2\Utility\GeocodeUtility does not exist

**Comment by froemken** [comment]
Hello @blueamerican 

I know that error. As maps2 is only suggested but not required by events2 anymore, I can't set a minimal version of maps2 anymore. We have removed GeocodeUtility completely and have moved functionality into a service. Please update maps2 to at least version 4.1.

Nice greetings

Stefan
