### ISSUE TITLE
Error with MySQL sql_mode ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by vjanoch** [jweiland-net/events2#5]
Hi Stefan,

we get an error if the MySQL setting ONLY_FULL_GROUP_BY is set. This setting seems to be the default for MySQL 5.7. 
See: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

  caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::sql_query' (53 chars)
   ERROR => 'Expression #53 of SELECT list is not in GROUP BY clause and contains nonaggr
      egated column 'my_cms.tx_events2_domain_model_day.uid' which is not functi
      onally dependent on columns in GROUP BY clause; this is incompatible with sq
      l_mode=only_full_group_by' (253 chars)
   lastBuiltQuery => 'SELECT tx_events2_domain_model_event.*, tx_events2_domain_model_day.uid as d
      ay, tx_events2_domain_model_day.day as dayDay FROM tx_events2_domain_model_e
      vent LEFT JOIN tx_events2_event_day_mm ON tx_events2_domain_model_event.uid=
      tx_events2_event_day_mm.uid_local LEFT JOIN tx_events2_domain_model_day ON t
      x_events2_event_day_mm.uid_foreign=tx_events2_domain_model_day.uid WHERE tx_
      events2_domain_model_event.top_of_list = 1 AND FIND_IN_SET(tx_events2_domain
      _model_event.pid, '37') AND tx_events2_domain_model_day.day = (SELECT day 
      	FROM tx_events2_domain_model_day LEFT JOIN tx_events2_event_day_mm ON tx
      _events2_domain_model_day.uid=tx_events2_event_day_mm.uid_foreign WHERE t
      x_events2_event_day_mm.uid_local = tx_events2_domain_model_event.uid AND 
      day >= 1474495200 ORDER BY tx_events2_domain_model_day.day ASC LIMI
      T 1) AND tx_events2_domain_model_event.deleted=0 AND tx_events2_domain_mo
      del_event.t3ver_state<=0 AND tx_events2_domain_model_event.pid<>-1 
      AND tx_events2_domain_model_event.hidden=0 AND tx_events2_domain_model_event
      .starttime<=1474547880 AND (tx_events2_domain_model_event.endtime=0 OR tx
      _events2_domain_model_event.endtime>1474547880) GROUP BY tx_events2_domai
      n_model_event.uid' (1215 chars)

Regards Vaci

**Comment by froemken** [comment]
Hello Vaci,

please understand that I can't patch that now. I have just updated my MAMP which was installed with MySQL 5.6.28. On all of our servers we have MySQL 5.6.19. On my Ubuntu based NUC I have MySQL 5.6.33.

Stefan

**Comment by froemken** [comment]
I'm just working at Version 2.0.0. I have refactored my queries so would be nice, if you can test current master again. Thank you.

Stefan

**Comment by froemken** [comment]
I'm closing this ticket now. Please open it again, if the error still exists.
