### ISSUE TITLE
Error Installing last TER-Version under T3 8.7 LTS

### ISSUE THREAD

**Issue by jacques2017** [jweiland-net/events2#61]
Hello,
I tried to install the last version in TER under T3 8.7LTS. After this the Message "An Error occured" is displaying in Backend.

**Comment by froemken** [comment]
Hello @jacques2017 

I have just uploaded version 3.0.3 to TER. Maybe it solves your problem.

We are using this extension in two big projects and I don't have any error-occurred messages in backend. Can you please activate Debug-Preset in Installtool to get further information about this error?

Stefan

**Comment by jacques2017** [comment]
Hallo Stefan,

thank you. This solves the problem. 

Jens
