### ISSUE TITLE
ical export bei wiederholenden Terminen

### ISSUE THREAD

**Issue by wowawebdesign** [jweiland-net/events2#65]
Ich habe mehrere Termine und möchte alle im ical export haben, nicht nur Start und Ende.

**Comment by froemken** [comment]
Problem ist, wenn es z.B. ein Musical gibt, das für 3 Monate jede Woche läuft, dann würden diese 12 gleichen Musicals alle im iCal landen. Der Webseitenbesucher weiß dann überhaupt nicht mehr, welcher Termin in seinem Outlook/iPhone/WhatEver für ihn interessant war. Würde ich so nicht umsetzen wollen.
Ich habe aber gerade noch einen Fehler im iCal Export gefunden und mit Version 3.0.6 behoben

**Comment by Schmalztopf** [comment]
Hallo,
ich hätte auch einen Anwendungsfall, in dem es sinnvoll wäre, mehrere Termine in ein ics zu packen. Kann man das nicht so machen, dass ics auf der Listenansicht den ganzen Kalender exportiert? Für einen wiederkehrenden Event, könnte man das dann ja weglassen. Es liegt doch in der Verantwortung des Editors, welche Termine er zum Download anbieten möchte, oder?
