### ISSUE TITLE
Wrong recurring events for past events

### ISSUE THREAD

**Issue by Ducrot** [jweiland-net/events2#7]
Wrong recurring events if recurringPast = 0 and/or history events.

Steps to reproduce:
- Extension-Manager recurringPast = 0
- Create a weekly recurring event with a date in the past which ist not the current day or weekday
- The generated day events are wrong.

The example screenshot.

![example](https://cloud.githubusercontent.com/assets/3525119/19314467/84fd9c32-909a-11e6-8972-a67c5abdda5b.png)

Event date: 11.7.2016 (Monday)
Events created at 12.10.2016
=> Generated dates: Tuesday

**Comment by froemken** [comment]
Hello Ducrot,

this is a heavy miss-configuration. You told events2 to NOT create events in the past, but you want to create an event in the past.

Stefan

**Comment by Ducrot** [comment]
Hello Stefan,

it was only a simplified example. Shouldn't look the datelist in the screenshot like this?

Montag
17.10.2016

Montag
25.10.2016

...


Because event_begin was also monday/Montag and not tuesday/Dienstag?

The event creation works for 3 month without problems (because of basic.recurringPast = 3). Now events older than 3 month have wrong (future) dates.


Kind regards
Christian

**Comment by froemken** [comment]
Hello @Ducrot 

another customer has problems with recurringPast = 0 and we solved it. Further we have updated the DayGenerator and solved some more problems. We have added many UnitTests for this and currently they all are green.

Stefan
