### ISSUE TITLE
Error in list view

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#79]
Hi, 
I use TYPO3 v9.5.3 + events2 v3.2

When I try to show events with the plugin 'list events' I get the following error:

`Fluid parse error in template partial_Event/Date_58bb0794d1cd026a64159cf1950b15147dd2bcb1, line 19 at character 3. Error: Required argument "value" was not supplied. (error code 1237823699). Template source chunk: <f:case default="1"> `

Regards
Hobokens

**Comment by Hobokens** [comment]
I changed in 'Partials/Event/Date.html'
```
<f:case default="1">
    <f:render section="date" arguments="{day: day.day}" />
</f:case>
```
to 
```
<f:case value="default">
    <f:render arguments="{day: day.day}" section="date"/>
</f:case>
```
This seems to solve the problem. But I get the following error message now:

`Class JWeiland\Maps2\Domain\Model\PoiCollection does not exist. Reflection failed.`

Thanks for any help.

Hobokens

**Comment by Hobokens** [comment]
I forgot to mention that I get the second error message only if I try to add a location to the event.

**Comment by froemken** [comment]
Your second problem is really ugly, as TYPO3 Fluid pre compiles everything found in templates. I have added a f:if VH to prevent rendering of Google Maps, if txMaps2Uid is empty, but TYPO3 tries to pre compile the inner part and of cause...if maps2 is not installed, it will throw an Exception.

This is a very old TYPO3 Fluid issue which I can't solve. But I can add this problem incl. solution into documentation.

As long as you don't make use of maps2, please remove that snippet from Location/Show.html template:

```
<f:if condition="{location.txMaps2Uid}">
	<maps2:widget.poiCollection poiCollection="{location.txMaps2Uid}" override="{settings: {mapWidth: '100%', mapHeight: '300', zoom: '14'}}" />
</f:if>
```

Stefan

**Comment by froemken** [comment]
I have added a new section "FAQ" into documentation where I describe why these three lines should be deleted.
