### ISSUE TITLE
Only show events in future based on Time

### ISSUE THREAD

**Issue by RonLeh** [jweiland-net/events2#92]
Hello Stefan,

is it possible to show only events which will be starting in the future, based on starttime?
For example: can I generate a listview which will not show an event from 10.00 o`clock in the morning when I visit the site at 12.00 o`clock?

Thank you very much!
Best regards Ron.

**Comment by froemken** [comment]
Go to extension manager and set the month past property to 0. With this value we are using current time and not midnight to select day records

**Comment by RonLeh** [comment]
Hello Stefan,
thank you very much! This works for me.

Best regards Ron.
